### PR TITLE
Fixing translation averaging for the panorama case

### PR DESCRIPTION
**Pull request by akshay-krishnan**
When the translation recovery class was used with unit translations that are all zero (all cameras at the same point), it would cause a segmentation fault. 
This PR adds a unit test for this case and fixes the segmentation fault.

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
Approved, but I'd like to know what the underlying GTSAM bug is that threw a segfault :-) We should fix that with an exception.

**Comment by dellaert** [comment]
Also, CI does not pass?

**Comment by johnwlambert** [comment]
> Also, CI does not pass?

Seems to be a homebrew issue, Fan suggested a fix and I put it in a different PR

**Comment by akshay-krishnan** [comment]
> Approved, but I'd like to know what the underlying GTSAM bug is that threw a segfault :-) We should fix that with an exception.

I believe the segfault was in TranslationRecovery::addPrior, [this line](https://github.com/borglab/gtsam/blob/759dcaa1dd9bd799c6a531561563acfa9ae5032b/gtsam/sfm/TranslationRecovery.cpp#L85) specifically. Using the first edge in the graph when it is empty.

**Comment by dellaert** [comment]
Ah, so it was your code, not GTSAM :-)

**Comment by johnwlambert** [comment]
@akshay-krishnan can you pull in develop?

**Pull request merged**
