### PR TITLE
Specialize BetweenFactor with Similarity3 for Python bindings

### PR DESCRIPTION
**Pull request by niwhsa9**
Fairly trivial PR but I needed a `BetweenFactor<Similarity3>` in Python so this adds the specialization in the interface file to be exported by wrap. I figured I'd post this here in case you want this upstream, but feel free to close if its not desired.

### CODE REVIEW

**Review by varunagrawal — APPROVED** [review]
LGTM

**Comment by niwhsa9** [comment]
hm, did not encounter the CI preprocessor error when I built locally. Will try to repro and fix next week.

**Comment by varunagrawal** [comment]
The issue in build is fixed by #1728. We'll try to land it ASAP and you can merge in the fix.

**Comment by niwhsa9** [comment]
just rebased on that, lets try running CI again

**Comment by varunagrawal** [comment]
Thanks for the contribution!

**Pull request merged**
