### PR TITLE
Cleaner ci

### PR DESCRIPTION
**Pull request by talregev**
Cleaner ci

### CODE REVIEW

**Comment by varunagrawal** [comment]
I don't think this is necessarily cleaner. Also we have special actions for push to develop which involve building the nightly packages.

**Comment by talregev** [comment]
> I don't think this is necessarily cleaner. Also we have special actions for push to develop which involve building the nightly packages.

It easier to develop and add new functionality when the CI is cleaner. (The same work for code).
I can bring the old functionality and leave it as only cleaner yaml code.
We can discuss it on different PR if you open minded to hear my side.
If you insist. I can close this PR.

**Comment by varunagrawal** [comment]
Fair point but the CI isn't the focus of improvement right now. Also since we're open source, we don't get paid CI instances so it's a premium resource.

We prefer to run all tests on a local machine first to get things working and then push a PR for a collective check.

Hope that makes sense. :)

**Comment by talregev** [comment]
I am not sure which of the option I suggested you wanted. For now I am closing this PR.

**Pull request closed without merging**
