### PR TITLE
Fix/warnings

### PR DESCRIPTION
**Pull request by dellaert**
Fixed warnings I found when compiling with latest clang.
This includes forgotten virtual destructor in Cal3.

### CODE REVIEW

**Review by varunagrawal — COMMENTED** [review]
Cool! Any reason we're switching from const references in the for-ranges to const values?

**Comment by dellaert** [comment]
> Cool! Any reason we're switching from const references in the for-ranges to const values?

The boost-created range functionality does not yield references. That's what the warning was.

**Comment by dellaert** [comment]
@varunagrawal when you approve, feel free to immediately merge.

**Review by varunagrawal — APPROVED** [review]
LGTM

**Pull request merged**
