### PR TITLE
Templated PoseToPointFactor

### PR DESCRIPTION
**Pull request by lucacarlone**
- [x] Template PoseToPointFactor
- [x] enable unit tests (before the test was .h and was not running)

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
Cool! Feel free to merge after the CI passes :-)

**Review by dwisth — APPROVED** [review]
Looks good to me @lucacarlone - it's a nice way to extend this factor to other use cases.

Same as Frank, I'm happy for you to merge once CI passes.

**Comment by dellaert** [comment]
I merged, even though one of the IC checks failed: I checked and it was an OS loading problem. 99.99% non-issue.

**Comment by lucacarlone** [comment]
that was fast! thanks @dellaert !

**Comment by dellaert** [comment]
Small PR's are always easier ;-)

**Pull request merged**
