### PR TITLE
Enable windows release build in the CI

### PR DESCRIPTION
**Pull request by varunagrawal**
@ds58 and I figured out that Eigen versions < 3.4.0 were causing the slow compile time (~2 hours) in the Release version for Windows.

Since we have updated the packaged Eigen to 3.4.0, we can re-enable the Windows Release Build CI.

### CODE REVIEW

**Comment by mikesheffler** [comment]
I tried a quick `Release` build in Visual Studio 2019. I did not take that long to build, but I did run into a `multiply defined symbols` error in linking `gtsam_unstable`:

```
Build started...
1>------ Build started: Project: gtsam_unstable, Configuration: Release x64 ------
1>gtsam.lib(gtsam.dll) : error LNK2005: "public: __cdecl std::map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >::~map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >(void)" (??1?$map@_K_KU?$less@_K@std@@V?$allocator@U?$pair@$$CB_K_K@std@@@2@@std@@QEAA@XZ) already defined in LPInitSolver.obj
1>   Creating library C:/Mike/Work/Build/gtsam/lib/Release/gtsam_unstable.lib and object C:/Mike/Work/Build/gtsam/lib/Release/gtsam_unstable.exp
1>C:\Mike\Work\Build\gtsam\gtsam_unstable\bin\Release\gtsam_unstable.dll : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "gtsam_unstable.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 69 up-to-date, 0 skipped ==========
```

**Comment by varunagrawal** [comment]
@mikesheffler I am getting the same issue but I can't for the life of me figure it out and I don't have the Windows expertise or the cycles to devote more time to it. :(

Since CI passes, can you please approve this and I can file an issue to tackle this in the future?

**Comment by mikesheffler** [comment]
Sounds good. It is also not immediately obvious to me what the issue is :/

**Review by mikesheffler — APPROVED** [review]
CI passes. @varunagrawal is going to file an issue related to a linking error that is coming up with `gtsam_unstable` in his (and my) local builds.

**Pull request merged**
