### PR TITLE
fix ambiguous template variadic variable issue

### PR DESCRIPTION
**Pull request by ShuangLiu1992**
fix fix ambiguous template variadic variable issue on non-gcc compilers https://stackoverflow.com/questions/56943558/c-partial-template-argument-deduction-for-function-with-variadic-pack-produces

### CODE REVIEW

**Comment by dellaert** [comment]
Thanks ! Let's wait for CI.
Is this also an issue in release/4.2 or is this due to changes in develop after we branched off the release?

**Review by dellaert — APPROVED** [review]

**Comment by dellaert** [comment]
@ShuangLiu1992 I merged but still interested in answer about 4.2. Thanks for your contribution, regardless!

**Comment by ShuangLiu1992** [comment]
Hi thanks for merging.
Previously I have been only compiling release [4.2a7](https://github.com/borglab/gtsam/releases/tag/4.2a7) and it was fine on all compilers I tested, recently started trying out the develop branch and notcied clang reporting this error. I haven't tried  [4.2a8](https://github.com/borglab/gtsam/releases/tag/4.2a8)

**Comment by varunagrawal** [comment]
I'm on 4.2 with clang and haven't received this error. We should still wait for @ShuangLiu1992 to report his results though.

**Comment by dellaert** [comment]
Actually, both are new methods added by Kartik and are not even in 4.2, so we can ignore. Thanks both!

**Pull request merged**
