### PR TITLE
Some refine works related to range-based for-loop of map constainer

### PR DESCRIPTION
**Pull request by zubingtan**
This PR:
1. reserve vector size in DecisionTreeFactor::apply
2. use auto in range-base for-loop to avoid implictly conversion in VectorValues and DecisionTreeFactor. Some format issues are address, too (add spaces).

### CODE REVIEW

**Comment by zubingtan** [comment]
@varunagrawal Can you help to take a look at the CI fails? 
image

Or, do I have to wait for approve to get rid of those fails?

**Comment by zubingtan** [comment]
@dellaert Can anyone help me to review this PR?

**Comment by dellaert** [comment]
@zubingtan for some reason the windows CI failed. Could you merge in the latest develop and push?

**Comment by zubingtan** [comment]
> @zubingtan for some reason the windows CI failed. Could you merge in the latest develop and push?

@dellaert  done. Could you help to tigger the CI pipeline again? thanks !

**Comment by dellaert** [comment]
So weird. I can't re-trigger. Maybe this is because of force-push? Can you just add a "dummy commit" (maybe reformat something slightly) and just "push" not force-push? stumped...

**Comment by zubingtan** [comment]
@dellaert Done. 

And then I realized we really don't have this `DefaultChart`, right? Anyway, I searched gtsam and couldn't find it

```
D:\a\gtsam\gtsam\gtsam/base/chartTesting.h(37,39): error C2760: syntax error: unexpected token '<', expected 'declaration' [D:\a\gtsam\gtsam\build\gtsam\gtsam.vcxproj]
```

image

**Comment by dellaert** [comment]
Right, but how does that only pop up now? @varunagrawal this is also a think in tour PR. any ideas? For a fix?

**Comment by zubingtan** [comment]
> Right, but how does that only pop up now? @varunagrawal this is also a think in tour PR. any ideas? For a fix?

How about I make a PR to delete `chartTesting.h`. It seems that nobody uses it.

**Comment by zubingtan** [comment]
> I wouldn't recommend deleting chartTesting since that's a symptom not the cause.
> 
> My gut says that something changed in the Actions Windows image and that change is causing this issue. I'll take a closer look at it.

However, `gtsam::DefaultChart<T>` is not in the codebase now. Maybe someone deleted `gtsam::DefaultChart<T>` before and forgot to delete chartTesting...

**Comment by varunagrawal** [comment]
@dellaert issue is related to a CMake command. I have added a fix at #1508

**Comment by dellaert** [comment]
Merge in develop to re-run windows CI?

**Comment by zubingtan** [comment]
> Merge in develop to re-run windows CI?

Done for merge, please help to re-trigger the CI. thanks~

**Pull request merged**
