### PR TITLE
Add cmake flag to include eigen-unsupported module

### PR DESCRIPTION
**Pull request by varunagrawal**
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/112)

### CODE REVIEW

**Comment by chrisbeall** [comment]
Unclear if there was a technical reason, but it looks like past Frank decided not to install unsupported Eigen modules here: https://bitbucket.org/gtborg/gtsam/pull-requests/331/feature-eigen-334

**Comment by varunagrawal** [comment]
@dellaert @chrisbeall what's the verdict on this? I am guessing once we have clarity, I can write it up and we can merge this in since it doesn't change existing functionality.

**Comment by dellaert** [comment]
CI passed for all configs so I am OK to include again, https://travis-ci.com/borglab/gtsam/builds/127250576

**Comment by dellaert** [comment]
Build CI passed, tests not affected, will merge.

**Pull request merged**
