### PR TITLE
Wrap Update

### PR DESCRIPTION
**Pull request by varunagrawal**
This update adds support to the Matlab wrapper for default arguments.

### CODE REVIEW

**Review by gchenfc — APPROVED** [review]

**Comment by varunagrawal** [comment]
Thanks for the review @gchenfc. I am going to let @mattking-smith submit a review before I merge. :)

**Review by mattking-smith — APPROVED** [review]
@gchenfc This work look terrific. Well cone.

**Comment by mattking-smith** [comment]
> Thanks for the review @gchenfc. I am going to let @mattking-smith submit a review before I merge. :)

I looked through everything. I do not see a problem with this. Feel free to merge @varunagrawal

**Comment by varunagrawal** [comment]
Now we just have to figure out the memory leak and we should be good to go with the Matlab wrapper 😄

**Pull request merged**
