### PR TITLE
[RFC] GTSAM ReadTheDocs site

### PR DESCRIPTION
**Pull request by jlblancoc**
Consider this a RFC to continue discussing the proposed structure of the docs:

* [online built web](https://gtsam-jlblanco-docs.readthedocs.io/en/latest/)

Explanation:
* Based on standard sphinx + rtd template + a customized "hack" to run Doxygen inside `conf.py` and allow browsing Doxygen documentation for all C++ classes.
* RST hand-written pages are under `/docs`
* I guess all docs under `/doc` should be removed and ported to Rest pages under `/docs`
* Doxygen docs: a lot of work is required to clean it up, e.g. organize all classes into groups, etc.

If/when merged, @dellaert  you'll have to login into readthedocs.io and add borglab/gtsam as one project with an URL like `{gtsam,gtsam-docs}.readthedocs.io`. All default options should work, since relevant settings are already specified via a `.readthedocs.yml` file.

I could keep porting existing docs to RST on spare time, or give someone else access to the fork, or you could merge and continue the development in this main repo.

PS: Build locally with: 

```bash
cd docs
make html
xdg-open build/html/index.html
```

### CODE REVIEW

**Comment by dellaert** [comment]
Very cool. Some points:

-  Now that the semester is starting, maybe we can have a meeting with both of you and all my students, and organize/distribute the work. 

-  I already ported a tutorial to gtsam.org, all in markdown. Can we use that as is, or does it have to be transcribed to RST.? 

- Any hope the doxygen code can end up in the readthedocs format? If not, is there another way to annotate the c++ code that is more compatible with readthedocs?

**Comment by jlblancoc** [comment]
Note to myself: the tutorial is this one:
http://gtsam.org/tutorials/intro.html

Frank:
- ok to talk with some of your students to have more helping hands!
- on integrating doxygen into rtd: afaik, it can be done with a server of
your own (I made it e.g. here
https://docs.mrpt.org/reference/latest/group_mrpt_graphslam_grp.html .
Running the same in the public rtd server... Perhaps could be done if some
of you know how to package a c++ binary project, already compiled, into
something that can be grabbed at their servers via pip... it's the only
plan I can devise without a custom server...

Cheers

**Comment by jlblancoc** [comment]
@dellaert
A heads up: I (partially) ported your tutorial to RST, you can see the results [here](https://gtsam-jlblanco-docs.readthedocs.io/en/latest/Tutorials.html). It still needs polishing (re-adding images, citations, etc.) but it's now, I think, easier as a starting point for some of your students if someone want to give a hand. 

Let me know if some of you needs some help in the process!

**Comment by dellaert** [comment]
Will do! what happened to the student volunteer that was helping us out at the start?

**Comment by jlblancoc** [comment]
> Will do! what happened to the student volunteer that was helping us out at the start?

He might be back someday, but he said they were really busy with field tests on his robotics PhD during September.

**Comment by dellaert** [comment]
So sad that this effort has stalled, @jlblancoc  :-) No student yet to help you bring this to fruition?

**Comment by pks-97** [comment]
Hey team, came across the post on LinkedIn regarding creating elaborate documentation for GTSAM. I would be happy to volunteer for it!

**Comment by edwardwterry** [comment]
Also here from LinkedIn. Count me in!

**Comment by jlblancoc** [comment]
Awesome! Give me time to get this particular branch in synch with the current develop, and I'll post instructions on how to work. I think it could be done ok by several contributors in parallel if we agree on which pages will work each one... thanks!! :100:

**Comment by jlblancoc** [comment]
> I have some prior SLAM experience, and I came across your linkedin post. I an happy to volunteer. Can I get some help getting started?

Thanks! Please follow the instructions and discussion in https://github.com/borglab/gtsam/discussions/1473

**Pull request merged**
