### PR TITLE
Fix stubs generation

### PR DESCRIPTION
**Pull request by varunagrawal**
Changed the stubgen command to use the default `out` directory since the custom directory doesn't seem to be working.

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
OK, I checked out this branch and that seems to be working.

**Comment by tianyilim** [comment]
Hi, could I know what configuration you use to get the stubs working? For me the type hinting has stopped working.

For instance, I do the following:

```python3
import gtsam

prior_noise = gtsam.gtsam.noiseModel.Diagonal.Sigmas( ...
```

And Pylance reports: `noiseModel" is not a known attribute of module "gtsam"`

I tried also using `gtsam.noiseModel` and importing as `from gtsam import noiseModel` and `import gtsam.gtsam as gtsam` etc. The code still runs fine, it's just the type hinting that's no longer working for me.

**Comment by ProfFan** [comment]
Hi @tianyilim is it the case that only `noiseModel` is not working and everything else works? If that is the case then it's because `pylance` recognizes the import path wrong.

Two questions:
1. If you say `prior_noise = gtsam.noiseModel.xxx()` does it work?
2. does it work if you `pip install gtsam-stubs` and restart vscode? (remember to uninstall it after you test it)

**Comment by tianyilim** [comment]
Hello @ProfFan:

1.  I seem to get import errors for most things:
    image

    VS Code auto suggestions look as follows (I guess straight from the `__init__.py` file)
    image

    And `gtsam.noiseModel` shows up as a class, but with no members:
    image

2. Installing `gtsam-stubs` seems to have made most of the typing errors go away.

**Comment by ProfFan** [comment]
Hi @tianyilim, could you try if #1821 works for you?

**Pull request merged**
