### PR TITLE
Release/4.2a4

### PR DESCRIPTION
**Pull request by dellaert**

### CODE REVIEW

**Review by johnwlambert — APPROVED** [review]
LGTM. Why are we using `master` instead of `develop` though?

**Comment by dellaert** [comment]
Thanks John. There are *two* PRs, one into master and one into develop. Please approve both :-)
See https://gtsam.org/notes/Contributing.html

**Comment by johnwlambert** [comment]
> Thanks John. There are _two_ PRs, one into master and one into develop. Please approve both :-) See https://gtsam.org/notes/Contributing.html

Got it, both are approved : - )

**Comment by ProfFan** [comment]
Release branches should be kept as is @dellaert

**Comment by dellaert** [comment]
I don't think so... Maybe discuss with me first?

**Comment by dellaert** [comment]
Gitflow convention is to tag and delete the branch, AFAIK.
But I see that we need it for manylinux build :-) That's a different issue, and glad you restored it.

**Pull request merged**
