### PR TITLE
Bump version to 4.0.2

### PR DESCRIPTION
**Pull request by Ellon**
Hi,

I noticed the version was not bumped after 4.0.2 release, so I bumped it on this PR.

It was also not bumped for 4.0.1... was this on purpose ?

Cheers!

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/130)

### CODE REVIEW

**Comment by dellaert** [comment]
We sometimes make little mistakes like this on purpose, just to keep people on their toes :-) Will merge and kill Travis builds

**Comment by Ellon** [comment]
Naughty developers... :laughing: Don't forget to update the tag then too. :wink: 

Cheers!

**Comment by dellaert** [comment]
Hmmm, updating a tag seems to be discouraged. Maybe a new tag 4.0.2a?

**Comment by dellaert** [comment]
Although that sounds like alpha.

**Comment by Ellon** [comment]
It is very discouraged... :/ Forcing the tag update would keep the repo in the "right state" (tag naming matching code version), but may mess with some clones/forks of the repo. Changing the tag name would make it look like a newer version, when in fact it's not.

Not sure what to do here... I think it will be up to you guys to chose one.

**Comment by Ellon** [comment]
Personally I would update the tag and warn the community about the mistake. I believe most of people using GTSAM would be able to handle this update.

**Comment by dellaert** [comment]
@varunagrawal could you move the tag and post to google group?

**Comment by dellaert** [comment]
GTSAM uses Gitflow, see https://nvie.com/posts/a-successful-git-branching-model/

**Comment by dellaert** [comment]
And https://gtsam.org/notes/Contributing.html :-)

**Comment by Ellon** [comment]
Oh, OK, so I messed up when I proposed the merge on top of master... :sweat_smile: Sorry about that. I'll take more care next time.

**Comment by varunagrawal** [comment]
Yup I'll do it.

**Pull request merged**
