### PR TITLE
Cherry-pick fixes from 4.2 release

### PR DESCRIPTION
**Pull request by varunagrawal**
This PR moves forward fixes made to the `release/4.2` branch so they are reflected in the latest `develop`.

### CODE REVIEW

**Comment by dellaert** [comment]
Hmmm, There is more than just hybrid here, you also made changes in cmake, which possibly conflicts with PR #1464  from Lawrence. Can you separate the cmake stuff in a different PR? Too many cooks at this moment.

**Comment by varunagrawal** [comment]
> Hmmm, There is more than just hybrid here, you also made changes in cmake, which possibly conflicts with PR #1464 from Lawrence. Can you separate the cmake stuff in a different PR? Too many cooks at this moment.

There should be no conflict since the files affected by each PR are mutually exclusive.

**Comment by dellaert** [comment]
Trusting you on the hybrid stuff, but what are the cmake changes in this PR?

**Comment by varunagrawal** [comment]
> Trusting you on the hybrid stuff, but what are the cmake changes in this PR?

Currently CMake prints the flags for all build types (Debug, Release, RelWithDebInfo, etc), which I found was pretty heavy and not quite informative, so I updated CMake to only print the flags for the current build type.

E.g. before:

```
--  C++ compilation flags                            :  -O3 -DNDEBUG
--  GTSAM_COMPILE_FEATURES_PUBLIC                    : cxx_std_17
--  GTSAM_COMPILE_OPTIONS_PUBLIC                     :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC                 :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_DEBUG               :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_DEBUG           :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_RELEASE             :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_RELEASE         :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_TIMING              :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_TIMING          :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_PROFILING           :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_PROFILING       :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_RELWITHDEBINFO      :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_RELWITHDEBINFO  :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_MINSIZEREL          :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_MINSIZEREL      :
--  Use System Eigen                                 : OFF (Using version: 3.4.0)
```

After
```
--  Enable Boost serialization                       : ON
--  GTSAM_COMPILE_FEATURES_PUBLIC                    : cxx_std_17
--  GTSAM_COMPILE_OPTIONS_PUBLIC                     :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC                 :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_RELEASE             :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_RELEASE         :
--  Use System Eigen                                 : OFF (Using version: 3.4.0)
```

**Review by dellaert — APPROVED** [review]
Cool!

**Comment by varunagrawal** [comment]
FYI this is the result for Debug config (as expected):
```
--  Enable Boost serialization                       : ON
--  GTSAM_COMPILE_FEATURES_PUBLIC                    : cxx_std_17
--  GTSAM_COMPILE_OPTIONS_PUBLIC                     :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC                 :
--  GTSAM_COMPILE_OPTIONS_PUBLIC_DEBUG               :
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_DEBUG           :
--  Use System Eigen                                 : OFF (Using version: 3.4.0)
```

**Pull request merged**
