### PR TITLE
More Expression wrappers

### PR DESCRIPTION
**Pull request by BrettRD**
This pull request adds Expressions for:
* Range<Point2, Point2>
* Pose3::transformPoseTo
* Pose3::translation
* Unit3::point3
* OrientedPlane3::distance
* OrientedPlane3::normal
* PinholeCamera::getPose

This pull request also adds Jacobians to the getter functions OrientedPlane3::distance and OrientedPlane3::normal

Let me know if any of these need tests, I couldn't spot any existing test patterns for these kinds of wrappers
I have some examples for these that I can share as well

### CODE REVIEW

**Comment by dellaert** [comment]
Awesome! No need to test the expressions, but the new derivatives in Unit3 should have a test :-) Are you up for adding those?

**Comment by BrettRD** [comment]
I can give it a whirl,
Do you mean the new derivatives in `OrientedPlane3.h`?
Would the test end up `testExpressionFactor.cpp`?

**Comment by dellaert** [comment]
Yep, those. They should be tested in `testOrientedPlane.cpp`, look at `TEST(OrientedPlane3, jacobian_retract)` for an example on using functions from `numericalDerivative.h`.

**Comment by BrettRD** [comment]
I was just thinking the explicit-value tests looked superfluous,
I'll try rebuilding those and actually refer to the tangent space

**Comment by BrettRD** [comment]
I think the new tests are what you're after.
I left in the test that compares to retract(zero) because it's fast and readable.

**Review by dellaert — APPROVED** [review]
Looks awesome ! Will merge when CI passes. Thanks !!!

**Pull request merged**
