### PR TITLE
Make sure our readme is proper restructuredText

### PR DESCRIPTION
**Pull request by ProfFan**
Otherwise pypi will not allow the wheel to be uploaded.

### CODE REVIEW

**Comment by varunagrawal** [comment]
We don't need restructured text for the Readme. We need to set a value in the setup.py to enable using markdown.

**Comment by varunagrawal** [comment]
Huh that change makes no sense to me...

**Comment by ProfFan** [comment]
@varunagrawal Oh I don't know if that is allowed :) Could you point me to a doc about this? I can change it really quick

**Comment by ProfFan** [comment]
Explanation: :: marks the next section to be code in restructuredText, so this table will become a code block and render proper restructuredText.

**Comment by varunagrawal** [comment]
Here we go: https://stackoverflow.com/a/26737258/1236990

I was most happy when this feature was released.

**Comment by ProfFan** [comment]
@varunagrawal Done :) Thanks for the heads up!

**Pull request merged**
