### PR TITLE
Fix MSVC Build in AppVeyor

### PR DESCRIPTION
**Pull request by ProfFan**
I cherry-picked this from the pybind wrapper PR. Hopefully this works...

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/375)

### CODE REVIEW

**Comment by varunagrawal** [comment]
Gonna wait till the AppVeyor CI passes. Will approve the moment it is done. :)

**Comment by ProfFan** [comment]
Yeah same thought... They are supposed to be "standard compliant", lol

**Comment by jlblancoc** [comment]
Testing against all compilers (and their version) is so picky... so good you found a solution that fast :+1:

**Comment by mikesheffler** [comment]
Right now, I'm getting

```
1>ImuFactorExample2.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl gtsam::demangle(char const *)" (?demangle@gtsam@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) referenced in function "public: virtual void __cdecl gtsam::GenericValue<class Eigen::Matrix<double,-1,1,0,-1,1> >::print(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?print@?$GenericValue@V?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@@gtsam@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
```

x ~ 1000 (`ImuFactorExample2` is the first one that caught my eye) when I build on MSVC 2017 right now. Related?

Another example:

```
10>ConcurrentCalibration.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl gtsam::demangle(char const *)" (?demangle@gtsam@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) referenced in function "public: virtual void __cdecl gtsam::GenericValue<class gtsam::Cal3_S2>::print(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?print@?$GenericValue@VCal3_S2@gtsam@@@gtsam@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
```

adding `#include <string>` doesn't seem to do the trick :(

**Comment by ProfFan** [comment]
I don't know if we are still able to support two VS versions, but I think the cause is some behavior change related to `GTSAM_EXPORT`... Could you try this patch and see if it changes anything? 

https://github.com/borglab/gtsam/pull/259/commits/a18a74778d8c1d2ec284dccecbe0ea7111a3747c

**Comment by mikesheffler** [comment]
Doesn't seem to help. 

Could you help me understand

> I don't know if we are still able to support two VS versions,`

? Am I using the wrong version of Visual Studio? I'm using the  Visual Studio 15 2017 generator because I thought that was what was being supported right now. Did I misunderstand? Now I'm trying the Visual Studio 16 2019 generator. And, just to double check, I'm using `x64`.

**Comment by jlblancoc** [comment]
The problem seems to be the lack of the `GTSAM_EXPORT` macro in demangle()... 
I'm opening a PR now.

**Comment by mikesheffler** [comment]
Thanks. I pulled and am testing now ...

**Comment by mikesheffler** [comment]
Looks like that might have done the trick. Thanks! What *is* the supported version of Visual Studio, by the way? I usually use GTSAM on Ubuntu, but I've been thinking about dusting off the Windows builds of some stuff where I used GTSAM.

**Comment by varunagrawal** [comment]
@jlblancoc thanks for finding the issue so quickly! We should start calling you Mr. Reliable.

That's actually a good question @mikesheffler. We just recently decided on a minimum supported version for Python and Ubuntu, so we should do the same exercise for Windows.

**Comment by jlblancoc** [comment]
> What is the supported version of Visual Studio, by the way? 

VS 2019 works: tested locally, and in AppVeyor. VS 2017 worked too, if I recall correctly, but it's not tested daily on AppVeyor so it's not a 100% statement ;-)

**Pull request merged**
