### PR TITLE
[RFC, WIP] Stabilize the New Pybind Wrapper

### PR DESCRIPTION
**Pull request by ProfFan**
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/349)

### CODE REVIEW

**Comment by dellaert** [comment]
Can we add pybind11 in a different branch/PR, and make that branch the target of this PR?
Also, does this PR have the latest changes to the cython wrapper?

**Comment by ProfFan** [comment]
> Can we add pybind11 in a different branch/PR, and make that branch the target of this PR?

Yes

> Also, does this PR have the latest changes to the cython wrapper?

No, I plan to add shortly

**Comment by ProfFan** [comment]
May need to open another one, as the diff is not updated, idk why.

**Comment by ProfFan** [comment]
@dellaert I think it is a bit hard to do that as I merged a lot of changes from develop, so GitHub's diff will show a lot of stuff from develop if I change the base to the one with only pybind.

**Comment by dellaert** [comment]
your pybind branch should be branched from develop.

**Comment by ProfFan** [comment]
@dellaert Yeah I tried that but GH is not updating the diff. I will try a different branch name and see if that works.

**Pull request closed without merging**
