### PR TITLE
[RFC, WIP] Stabilize the New Pybind Wrapper #2

### PR DESCRIPTION
**Pull request by ProfFan**
This PR aims to merge the new pybind11 based wrapper into `develop` so we can start letting people test them and reach a stable release.

Plan:
* [x] (In this PR) make sure that all tests (old and new wrapper) pass
* [x] Make sure that all tests and examples of old wrapper have a Doppelgänger in new wrapper
* [ ] Merge this PR & profit

Please feel free to comment if you have any comments for this PR :)

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/354)

### CODE REVIEW

**Comment by dellaert** [comment]
Hate to do this to you, but again I'm asking to split the PR: one with only the new wrapper generation code and its associated tests, the other with gtsam-related files (like tests and examples).

**Comment by ProfFan** [comment]
@dellaert  Sure, let me see how to do that.

**Comment by jlblancoc** [comment]
You could create a new local brach out from develop, then use git
cherrypick with the list of desired commits to include. Repeat again for
second or more branches.

**Comment by ProfFan** [comment]
It appears that the Windows build in the Actions CI is broken because of some possible upgrade of Visual Studio version? I don't have a Windows installation locally so I cannot test.

CC @jlblancoc @varunagrawal for advice :)

**Comment by ProfFan** [comment]
> You could create a new local brach out from develop, then use git cherrypick with the list of desired commits to include. Repeat again for second or more branches. El mié., 17 jun. 2020 2:30,

Thanks for the advice!

**Comment by ProfFan** [comment]
Travis is running out of memory building the pybind wrapper, otherwise I think it's good to go and I'll start splitting the PR.

**Comment by ProfFan** [comment]
All Cython examples and tests are migrated to Pybind, and I have tested MATLAB wrapper. I feel maybe it's time to just squash and merge this PR, as it's really a lot of work to try splitting it...

**Comment by dellaert** [comment]
I'm worried about this, however, especially about forgetting changes to cython examples over the past few months. I thought about it and I have a scheme that seems simpler and not a lot of tedious pulling apart:

- [ ] make a PR 1 that moves the cython code to the new location. Make sure install still works. 
- [ ] Review and merge that with no impact to existing cython wrapper.
- [ ] make a PR 2 that replaces this with the new python code. This should make explicit what the (not too many) changes are.
- [ ] @varunagrawal and I review PR 2
- [ ] make a squash PR 3 which omits the new python code, and which targets the PR2 branch.
- [ ] @varunagrawal and I review PR 3
- [ ] we merge PR 3
- [ ] we merge PR 2

**Comment by dellaert** [comment]
Yay ! Please request a review of the PR's when you think it's ready, in the order you want me to review them :-)

**Comment by ProfFan** [comment]
@jlblancoc Could you take a look on the CI failures on VS2019? I have a rough idea (https://github.com/iclcv/icl/issues/13), but I have no Windows with VS2019 to confirm...

**Comment by ProfFan** [comment]
Merged with #477

**Pull request closed without merging**
