### PR TITLE
Plotting for new python wrapper

### PR DESCRIPTION
**Pull request by varunagrawal**
This PR adds new plotting capabilities to the new PyBind11 based python wrapper. It mirrors the plotting functionality from the cython wrapper.

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/293)

### CODE REVIEW

**Comment by dellaert** [comment]
I'll let @ProfFan review

**Comment by varunagrawal** [comment]
Pretty much. I am not fully familiar with the new wrapper so decided to get Fan's feedback. Most of the plotting code is matplotlib specific so I don't imagine many core changes.

**Comment by ProfFan** [comment]
Just seen this, sorry for the late reply but I think it's not necessary to have this PR, as I will merge these periodically from develop... @varunagrawal @dellaert  I think that would be much easier for me to manage the workflow.

**Comment by varunagrawal** [comment]
@ProfFan sounds good to me. I'll close this since we can always reopen this PR when needed.

**Comment by ProfFan** [comment]
@varunagrawal I didn't realize that this is for the Python thingy! Sorry for that, let's merge this! Also, kudos for the work!

**Comment by dellaert** [comment]
@ProfFan will you merge and delete the branch?
@varunagrawal please delete branches after you merge them - lots of stale branches in code.

**Pull request merged**
