### PR TITLE
Wrap additional ISAM2 methods

### PR DESCRIPTION
**Pull request by varunagrawal**
Wrapping additional methods in ISAM2 needed for legged state estimation.

### CODE REVIEW

**Review by dellaert — CHANGES_REQUESTED** [review]
Confused. Most additions are commented out. Make draft PR until finalized.

**Comment by varunagrawal** [comment]
Okay removed out the commented stuff. That was my mistake, I added those in as part of another change not related to this PR. Thank you for catching them. :slightly_smiling_face:

**Review by dellaert — APPROVED** [review]
LGTM, but is that the only method you want to add? Are there others public methods that could easily be added in the same PR?

**Comment by varunagrawal** [comment]
No other methods so far that we need for MHS + State Estimator. If we find something, we can make a PR for then.

**Comment by dellaert** [comment]
My question was not about MHS, but expanding this PR to include other methods now that are easily wrapped.

**Comment by varunagrawal** [comment]
We can. It just depends on the requirements. My comment about MHS is that the current wrapped method is all I need so I didn't spend too much time looking at other methods.

**Review by dellaert — CHANGES_REQUESTED** [review]
OK, you're (choosing) to not hear me :-) For this *GTSAM* PR, please also wrap any other easy wrap-able functions before merging, so GTSAM users have this convenience in the future.

**Comment by varunagrawal** [comment]
Gotcha

**Review by dellaert — APPROVED** [review]

**Comment by dellaert** [comment]
Cool, thanks !!!

**Pull request merged**
