### PR TITLE
Implement `errorTree` in `DiscreteFactor`

### PR DESCRIPTION
**Pull request by varunagrawal**
Common base class method to reduce duplication.

### CODE REVIEW

**Review by dellaert — COMMENTED** [review]
Hmmmm. I'm worried about complexity here, *especially* if we have pruned branches. I think you replaced a sometimes errorTree with an always expensive version.

**Comment by varunagrawal** [comment]
> Hmmmm. I'm worried about complexity here, _especially_ if we have pruned branches. I think you replaced a sometimes errorTree with an always expensive version.

Interesting. I copy-pasted the code from `DecisionTreeFactor` to `DiscreteFactor` since `TableFactor` was anyway calling the `DecisionTreeFactor` version.
I didn't see this potential issue because except for `discreteKeys` there is no class specific method being used here. And `discreteKeys` should be the same for both `DiscreteFactor` and `DecisionTreeFactor`.

Maybe the original implementation was already expensive to begin with?

**Comment by dellaert** [comment]
Actually, you are right! We should just call the DecisionTree constructor in the DTF. That is a potential speedup! So, I like your base class implementation for generic, but it should speed up for derived class. Probably also in TableFactor: is toDecisionTreeFactor efficient?

**Comment by varunagrawal** [comment]
> Probably also in TableFactor: is toDecisionTreeFactor efficient?

It should be. It's from @ywkim0606's original PR which you had worked on with him.

**Review by dellaert — APPROVED** [review]

**Pull request merged**
