### PR TITLE
Wrap KeyVector methods

### PR DESCRIPTION
**Pull request by varunagrawal**
The title. This is needed for MHS.

We're also going to need to publish the latest version of the python package so that the CI can run successfully.

### CODE REVIEW

**Comment by dellaert** [comment]
> The title. This is needed for MHS.
> 
> We're also going to need to publish the latest version of the python package so that the CI can run successfully.

Explain comment about CI, it should not depend on a python package

**Comment by varunagrawal** [comment]
The MHS CI pulls the GTSAM python package for efficiency rather than build the wrapper from scratch. If we wrap something new, that's not already available on PyPI and so we need to push the latest package to PyPI

**Comment by johnwlambert** [comment]
> The MHS CI pulls the GTSAM python package for efficiency rather than build the wrapper from scratch. If we wrap something new, that's not already available on PyPI and so we need to push the latest package to PyPI

Yeah our pypi version is ancient. What's our current versioning policy? Are we on 4.1 or 4.0.1?

**Comment by ProfFan** [comment]
4.1 is still not released, but maybe we should push another pre release

**Comment by varunagrawal** [comment]
Then let's merge this and get to it?

**Review by ProfFan — APPROVED** [review]

**Comment by dellaert** [comment]
> The MHS CI pulls the GTSAM python package for efficiency rather than build the wrapper from scratch. If we wrap something new, that's not already available on PyPI and so we need to push the latest package to PyPI

OK, you should probably specify it won't affect *GTSAM* CI. This is a GTSAM PR.

**Comment by varunagrawal** [comment]
Gotcha. I mentioned this was needed for MHS but in my head I figured it was implied.

**Pull request merged**
