### PR TITLE
Fix wrapper warnings

### PR DESCRIPTION
**Pull request by varunagrawal**
Fix some warnings from `gtsam_unstable.i` due to the update to `NoiseModelFactorN`.

### CODE REVIEW

**Comment by varunagrawal** [comment]
Fixed some additional deprecation warnings as well which are internal to factor implementations, so it shouldn't affect the external API.

**Review by dellaert — APPROVED** [review]

**Review by gchenfc — APPROVED** [review]
Thanks!  My bad missing these, I think I had turned off unstable for wrappers

Clever use of template in gtsam_unstable.i : IMUFactor 😂

**Comment by varunagrawal** [comment]
Hey man, I'm not a GTSAM wrapper expert without reason. 😎

**Comment by varunagrawal** [comment]
Also no worries. This is why we have labmates to support one other. :)

**Pull request merged**
