### PR TITLE
Replace Travis CI and Appveyor with Github Actions

### PR DESCRIPTION
**Pull request by varunagrawal**

### CODE REVIEW

**Comment by ProfFan** [comment]
@varunagrawal I thought we are cherry-picking the commit from `feature/new_wrapper`? I think I can handle it today.

**Comment by varunagrawal** [comment]
@ProfFan yeah there were a looooot of commits to go through and this seemed faster.

**Comment by ProfFan** [comment]
@varunagrawal I propose that I take over, the Python build in this PR is for the pybind wrapper.

**Comment by varunagrawal** [comment]
I updated the scripts and the yml files to work with the Cython wrapper. So far everything seems to be working.

It honestly doesn't matter to me which of us works on this as long as we land this quickly. :)

**Comment by dellaert** [comment]
@ProfFan is right - better coordination here is needed to avoid double work :-(

**Comment by varunagrawal** [comment]
Alternatively, @ProfFan can merge off the latest develop and update this (some minor modifications, specifically only PyBind11 related).

I have added a bunch of fixes to ensure the checks work correctly (which the Pybind PR doesn't have).

**Comment by dellaert** [comment]
> Alternatively, @ProfFan can merge off the latest develop and update this (some minor modifications, specifically only PyBind11 related).
> 
> I have added a bunch of fixes to ensure the checks work correctly (which the Pybind PR doesn't have).

@varunagrawal  The issue seems to be that you guys did not coordinate (and your message does not indicate you are coordinating now) so the changes are somehow incompatible. Let's stop having the conversation here and connect with @ProfFan directly to decide how to do it.

**Comment by varunagrawal** [comment]
Deffered to #472

**Pull request closed without merging**
