### PR TITLE
Robust triangulation

### PR DESCRIPTION
**Pull request by lucacarlone**
Added option to use robust noise model during triangulation.

### CODE REVIEW

**Review by dellaert — COMMENTED** [review]
Very cool! Also asking a review from John ~~Travis~~, more as an FYI. (Travis is not yet on GTSAM, apparently)

**Review by johnwlambert — APPROVED** [review]
Very nice. LGTM

**Comment by lucacarlone** [comment]
@dellaert @johnwlambert thanks! I'll wait for @marcusabate to give it a try before merging.

**Comment by johnwlambert** [comment]
Hi @marcusabate could you take a look when you get a chance? This PR will be immediately useful for GTSFM so the sooner we can merge it, the better : - )

**Review by dellaert — APPROVED** [review]
Awesome!

**Pull request merged**
