### PR TITLE
Update geometry.i : wrap multiplication of Rot3 and Unit3 

### PR DESCRIPTION
**Pull request by akshay-krishnan**

### CODE REVIEW

**Comment by varunagrawal** [comment]
@akshay-krishnan please add some unit tests and I will happily approve this. :)

**Comment by varunagrawal** [comment]
@akshay-krishnan any updates on this? We're looking to release a new version, and if you can finish up the unit tests, let's land this so it can be included in the 4.2 release.

**Comment by akshay-krishnan** [comment]
Thanks for the reminder Varun, I'll update it today

**Comment by akshay-krishnan** [comment]
@varunagrawal I could not wrap the * operator, got the error "no supported * operator between Rot3 and Unit3", although I added the method in geometry.i (see my first commit). 

So I had to remove that, rotate() and unrotate() are fine, and apparently * operator is not wrapped for Point3 either.

**Review by varunagrawal — APPROVED** [review]
LGTM

**Comment by varunagrawal** [comment]
> @varunagrawal I could not wrap the * operator, got the error "no supported * operator between Rot3 and Unit3", although I added the method in geometry.i (see my first commit).
> 
> So I had to remove that, rotate() and unrotate() are fine, and apparently * operator is not wrapped for Point3 either.

Huh that's strange. I can take a look at it later maybe? Super swamped.

**Pull request merged**
