### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by varunagrawal**
A bunch of niceness regarding README files as well as an ISSUE template for Github to start out with.

### CODE REVIEW

**Comment by varunagrawal** [comment]
I wanted to get your opinion on what was a good issue template format before committing too much time to it. I can start off with the default message from Bitbucket.

**Comment by varunagrawal** [comment]
@dellaert updated the issue templates.

**Comment by dellaert** [comment]
Cool! Where are the two markdown files referenced?

**Comment by varunagrawal** [comment]
They should be in `.github/ISSUE_TEMPLATE`. There are different templates for the kind of issue to be reported (bug report vs feature request vs general support).

**Comment by dellaert** [comment]
Ah, but they're not... They're in `.github`

**Comment by varunagrawal** [comment]
Good catch. I've updated them.

**Pull request merged**
