### PR TITLE
Add python type annotations to some older python files

### PR DESCRIPTION
**Pull request by johnwlambert**
- Add type hints per PEP 484 (https://google.github.io/styleguide/pyguide.html#221-type-annotated-code). Some were previous added as part of docstring. These cannot be used for static analysis, so moved to function signature itself.
- remove dangerous wildcard imports
- fix some erroneous docstrings
- add some keyword args for readability

Files affected: 
- test_Pose3SLAMExample.py
- circlePose3.py
- plot.py
- visual_data_generator.py

### CODE REVIEW

**Review by ProfFan — APPROVED** [review]
It appears that the Python unit tests are failing, but otherwise looks good :)

**Comment by johnwlambert** [comment]
> It appears that the Python unit tests are failing, but otherwise looks good :)

thanks @ProfFan, should be fixed now

**Comment by ProfFan** [comment]
Noice!

**Comment by varunagrawal** [comment]
There's a missing import for `Pose3` that was introduced in this PR. We really need to add more Python tests.

**Comment by varunagrawal** [comment]
Also, @johnwlambert what formatter are you using? We all use yapf in case you use something else.

**Pull request merged**
