### PR TITLE
adding functionality to use ISAM2 for imu preintegration example

### PR DESCRIPTION
**Pull request by kvmanohar22**
In reference to #262. I have made the changes to use ISAM2. 

I used macros to check for the usage of ISAM2 since finding arguments was getting a bit cluttered.

Let me know if any changes are to be done!

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/263)

### CODE REVIEW

**Comment by dellaert** [comment]
Can you show output when using iSAM and LM, so we can compare ?

**Comment by kvmanohar22** [comment]
I obtained the following plots for the errors. The differences seem very subtle

pos_error
w_error

**Comment by dellaert** [comment]
Yeah, I don't even see any red? :-)

**Comment by kvmanohar22** [comment]
They seem to be quite identical albeit with subtle differences. Following is the data ;

```
[ 30%] Built target metis
[100%] Built target gtsam
Scanning dependencies of target ImuFactorsExample
[100%] Building CXX object examples/CMakeFiles/ImuFactorsExample.dir/ImuFactorsExample.cpp.o
[100%] Linking CXX executable ImuFactorsExample
[100%] Built target ImuFactorsExample
Using ISAM2
using default CSV file
initial state:
0 0 0 0 0 0 0 0 0 1

Position error:0.004	 Angular error:5.00001e-16
Position error:0.829697	 Angular error:2.85707e-07
Position error:1.51764	 Angular error:4.45785e-06
Position error:2.05642	 Angular error:2.39327e-05
Position error:2.43048	 Angular error:8.11728e-05
Position error:2.64067	 Angular error:0.00021199
Position error:2.70797	 Angular error:0.000467576
Position error:2.66587	 Angular error:0.000916839
Position error:2.54995	 Angular error:0.00164911
Position error:2.3905	 Angular error:0.0027767
Position error:2.2097	 Angular error:0.00443659
Position error:2.02179	 Angular error:0.00678997
Position error:1.83464	 Angular error:0.0100181
Position error:1.65147	 Angular error:0.0143118
Position error:1.47227	 Angular error:0.0198496
Position error:1.29496	 Angular error:0.0267605
Position error:1.11632	 Angular error:0.0350638
Position error:0.93293	 Angular error:0.0445864
Position error:0.742391	 Angular error:0.0548783
Position error:0.544806	 Angular error:0.0651216
Position error:0.343764	 Angular error:0.0742276
Position error:0.147413	 Angular error:0.0809386
Position error:0.0416614	 Angular error:0.0841892
Position error:0.195322	 Angular error:0.0834643
Position error:0.320031	 Angular error:0.0788364
Position error:0.409414	 Angular error:0.0709906
Position error:0.464623	 Angular error:0.0609017
Position error:0.489896	 Angular error:0.0495526
Position error:0.490729	 Angular error:0.0377666
Position error:0.472502	 Angular error:0.026145
Position error:0.439916	 Angular error:0.0150886
Position error:0.396674	 Angular error:0.00484153
Position error:0.345772	 Angular error:0.0044422
Position error:0.289617	 Angular error:0.0126696
Position error:0.230248	 Angular error:0.0197775
Position error:0.169498	 Angular error:0.0257213
Position error:0.109115	 Angular error:0.030471
Position error:0.0507742	 Angular error:0.034017
Position error:0.00428787	 Angular error:0.0363746
Position error:0.0537403	 Angular error:0.0375902
Position error:0.097252	 Angular error:0.0377436
Position error:0.133706	 Angular error:0.0369452
Position error:0.162577	 Angular error:0.0353296
Position error:0.1837	 Angular error:0.0330473
Position error:0.197228	 Angular error:0.0302531
Position error:0.203585	 Angular error:0.0270997
Position error:0.203398	 Angular error:0.023729
Position error:0.197417	 Angular error:0.0202672
Position error:0.186494	 Angular error:0.0168254
Position error:0.1715	 Angular error:0.0134954
Position error:0.153322	 Angular error:0.0103535
Position error:0.132824	 Angular error:0.00745986
Position error:0.110844	 Angular error:0.00486048
Position error:0.0881631	 Angular error:0.00258814
Position error:0.065509	 Angular error:0.000663213
Position error:0.0435395	 Angular error:0.00090532
Position error:0.0228312	 Angular error:0.00211905
Position error:0.00392405	 Angular error:0.00298932
Position error:0.0130291	 Angular error:0.0035361
Position error:0.0274592	 Angular error:0.00378659
Position error:0.0393188	 Angular error:0.0037739
Position error:0.0485247	 Angular error:0.00353526
Position error:0.0550963	 Angular error:0.00311029
Position error:0.0591364	 Angular error:0.00253976
Position error:0.0608189	 Angular error:0.00186366
Position error:0.0603748	 Angular error:0.00112022
Position error:0.0580775	 Angular error:0.000344738
Position error:0.0542295	 Angular error:0.000431041
Position error:0.0491478	 Angular error:0.00117976
Position error:0.0431528	 Angular error:0.00187856
Position error:0.0365578	 Angular error:0.00250934
Position error:0.0296583	 Angular error:0.00305876
Position error:0.0227249	 Angular error:0.00351807
Position error:0.015997	 Angular error:0.00388281
Position error:0.00967982	 Angular error:0.00415241
Position error:0.00394393	 Angular error:0.00432974
Position error:0.00118188	 Angular error:0.00442055
Position error:0.00539879	 Angular error:0.00443291
Position error:0.00882798	 Angular error:0.00437662
Position error:0.0114187	 Angular error:0.00426261
Position error:0.0131889	 Angular error:0.00410241
Position error:0.0141852	 Angular error:0.00390767
Position error:0.0144764	 Angular error:0.00368968
Position error:0.0141487	 Angular error:0.00345903
Position error:0.0132995	 Angular error:0.0032253
Position error:0.0120331	 Angular error:0.00299686
Position error:0.0104556	 Angular error:0.00278071
Position error:0.00867023	 Angular error:0.0025824
Position error:0.00677554	 Angular error:0.00240605
Position error:0.00486046	 Angular error:0.00225433
Position error:0.00300354	 Angular error:0.00212863
Position error:0.00127416	 Angular error:0.00202913
Position error:0.000346389	 Angular error:0.00195497
Position error:0.0016585	 Angular error:0.00190446
Position error:0.00276787	 Angular error:0.00187522
Position error:0.00363096	 Angular error:0.00186438
Position error:0.00424575	 Angular error:0.00186877
Position error:0.00462149	 Angular error:0.00188508
Position error:0.00477593	 Angular error:0.00191004
Position error:0.0047334	 Angular error:0.00194049
Complete, results written to imuFactorExampleResults.csv

[100%] Built target ImuFactorsExample.run
```

```
[ 30%] Built target metis
[100%] Built target gtsam
[100%] Built target ImuFactorsExample
Using Levenberg Marquardt Optimizer
using default CSV file
initial state:
0 0 0 0 0 0 0 0 0 1

Position error:0.004	 Angular error:5e-16
Position error:0.829697	 Angular error:2.85707e-07
Position error:1.51764	 Angular error:4.45774e-06
Position error:2.05642	 Angular error:2.39327e-05
Position error:2.43048	 Angular error:8.11728e-05
Position error:2.64067	 Angular error:0.00021199
Position error:2.70797	 Angular error:0.000467576
Position error:2.66587	 Angular error:0.00091684
Position error:2.54995	 Angular error:0.00164911
Position error:2.3905	 Angular error:0.00277671
Position error:2.2097	 Angular error:0.00443662
Position error:2.02179	 Angular error:0.00679005
Position error:1.83464	 Angular error:0.0100183
Position error:1.65147	 Angular error:0.0143121
Position error:1.47227	 Angular error:0.0198503
Position error:1.29496	 Angular error:0.0267616
Position error:1.11631	 Angular error:0.0350651
Position error:0.932923	 Angular error:0.0445882
Position error:0.742407	 Angular error:0.0548745
Position error:0.544794	 Angular error:0.0651228
Position error:0.343795	 Angular error:0.0742199
Position error:0.147454	 Angular error:0.0809235
Position error:0.0414223	 Angular error:0.0841781
Position error:0.195127	 Angular error:0.0834366
Position error:0.319866	 Angular error:0.0788113
Position error:0.409277	 Angular error:0.0709745
Position error:0.464529	 Angular error:0.0608926
Position error:0.489857	 Angular error:0.0495485
Position error:0.490724	 Angular error:0.037765
Position error:0.472522	 Angular error:0.0261446
Position error:0.439915	 Angular error:0.0150871
Position error:0.396673	 Angular error:0.0048413
Position error:0.345775	 Angular error:0.00444219
Position error:0.289623	 Angular error:0.0126695
Position error:0.230254	 Angular error:0.0197777
Position error:0.169507	 Angular error:0.0257214
Position error:0.109122	 Angular error:0.0304713
Position error:0.0507796	 Angular error:0.0340173
Position error:0.00430321	 Angular error:0.0363749
Position error:0.0537401	 Angular error:0.0375906
Position error:0.0972529	 Angular error:0.0377441
Position error:0.133707	 Angular error:0.0369458
Position error:0.162579	 Angular error:0.0353303
Position error:0.183703	 Angular error:0.0330478
Position error:0.197234	 Angular error:0.0302538
Position error:0.203592	 Angular error:0.0271005
Position error:0.203402	 Angular error:0.0237295
Position error:0.197423	 Angular error:0.0202679
Position error:0.186498	 Angular error:0.0168258
Position error:0.171504	 Angular error:0.0134958
Position error:0.153326	 Angular error:0.0103539
Position error:0.13283	 Angular error:0.00746024
Position error:0.110849	 Angular error:0.00486086
Position error:0.0881677	 Angular error:0.00258847
Position error:0.0655135	 Angular error:0.000663486
Position error:0.0435433	 Angular error:0.000905074
Position error:0.022835	 Angular error:0.00211884
Position error:0.00392913	 Angular error:0.00298915
Position error:0.0130261	 Angular error:0.00353596
Position error:0.0274569	 Angular error:0.00378652
Position error:0.0393165	 Angular error:0.00377389
Position error:0.0485233	 Angular error:0.00353528
Position error:0.0550957	 Angular error:0.00311041
Position error:0.0591365	 Angular error:0.00253991
Position error:0.0608195	 Angular error:0.00186383
Position error:0.0603758	 Angular error:0.00112038
Position error:0.0580788	 Angular error:0.000344908
Position error:0.0542307	 Angular error:0.000430911
Position error:0.049149	 Angular error:0.00117965
Position error:0.0431541	 Angular error:0.00187846
Position error:0.0365588	 Angular error:0.00250926
Position error:0.0296589	 Angular error:0.00305871
Position error:0.0227251	 Angular error:0.00351804
Position error:0.015997	 Angular error:0.00388279
Position error:0.00967912	 Angular error:0.00415241
Position error:0.00394137	 Angular error:0.00432976
Position error:0.00117344	 Angular error:0.00442058
Position error:0.00539753	 Angular error:0.00443296
Position error:0.00882776	 Angular error:0.00437667
Position error:0.011419	 Angular error:0.00426267
Position error:0.0131895	 Angular error:0.00410247
Position error:0.014186	 Angular error:0.00390773
Position error:0.0144774	 Angular error:0.00368973
Position error:0.0141498	 Angular error:0.00345907
Position error:0.0133008	 Angular error:0.00322533
Position error:0.0120345	 Angular error:0.00299689
Position error:0.0104569	 Angular error:0.00278073
Position error:0.00867204	 Angular error:0.00258242
Position error:0.00677776	 Angular error:0.00240605
Position error:0.00486347	 Angular error:0.00225433
Position error:0.00300834	 Angular error:0.00212863
Position error:0.00128488	 Angular error:0.00202912
Position error:0.000382045	 Angular error:0.00195497
Position error:0.00166583	 Angular error:0.00190446
Position error:0.00277197	 Angular error:0.00187521
Position error:0.00363383	 Angular error:0.00186437
Position error:0.00424796	 Angular error:0.00186876
Position error:0.00462327	 Angular error:0.00188508
Position error:0.00477742	 Angular error:0.00191004
Position error:0.00473466	 Angular error:0.00194049
Complete, results written to imuFactorExampleResults.csv

[100%] Built target ImuFactorsExample.run
```

**Comment by varunagrawal** [comment]
I might actually hijack this PR since I need the same functionality. Having an example would help save a lot of time in terms of having a template.

**Comment by dellaert** [comment]
> I might actually hijack this PR since I need the same functionality. Having an example would help save a lot of time in terms of having a template.

This PR came at a very busy time. Before merging, at the very least use a command line Argument? And, if you have time, I would (a) do command line parsing in a small main at bottom, as well as move all constants to the top, and properly name them (kSomethingOrOther).

**Comment by varunagrawal** [comment]
Yup, I plan to follow the process of the existing examples and ensure consistency (Two Birds, One Stone). :slightly_smiling_face:

**Comment by varunagrawal** [comment]
So I am a bit confused. There seem to be 3 examples of using IMU Factors already in the code base.

1. [ImuFactorsExample.cpp](https://github.com/borglab/gtsam/blob/75ce6d60ef6a7c8e0ec076b3602a7e5c215c4312/examples/ImuFactorsExample.cpp)

    Solid example. Has @lucacarlone as an author so I fairly trust its correctness. Options for both `ImuFactor` and `CombinedImuFactor`. Uses LM as the optimizer.

2. [ImuFactorsExample2.cpp](https://github.com/borglab/gtsam/blob/75ce6d60ef6a7c8e0ec076b3602a7e5c215c4312/examples/ImuFactorExample2.cpp)

    This is a version using `ISAM2` with the `ImuFactor` (no support for `CombinedImuFactor`). The example is synthetic since it uses a `Scenario` simulator.

3. [ISAM2_SmartFactorStereo_IMU.cpp](https://github.com/borglab/gtsam/blob/75ce6d60ef6a7c8e0ec076b3602a7e5c215c4312/examples/ISAM2_SmartFactorStereo_IMU.cpp)

    This seems to be an example that most closely resembles the example from the paper. Uses `ISAM2` with `CombinedImuFactor` and the `SmartStereoProjectionPoseFactor`. Some obvious bugs in the implementation (every new initial estimate at a keyframe is initialized using identity pose and zero velocity, rather than initializing from the previous estimate).

I guess updating 3 and making it work well would be the right way to go about creating an example. Ideally the input file should also have the ground truth data (we can generate it if necessary) so we can run a comparison.

@dellaert @kvmanohar22 thoughts?

**Comment by dellaert** [comment]
@varunagrawal I'm confused now :-) Are you proposing to decline this PR?

**Comment by varunagrawal** [comment]
Not decline, but perhaps rethink what needs to be done?

**Comment by dellaert** [comment]
I don't have bandwidth

**Pull request merged**
