### PR TITLE
Enable pickling

### PR DESCRIPTION
**Pull request by varunagrawal**
Enable pickling so we can deep copy a bunch of things in the Python wrapper.

The wrapper expects declaration of the `pickle` method in the interface file and will use the underlying `serialize` method of the class. The wrapper has had this feature for a while, but the classes updated in this PR didn't have the pickling enabled.

### CODE REVIEW

**Review by dellaert — CHANGES_REQUESTED** [review]
How does this PR enable pickling? Does this rely on functionality in wrap? Is that the wrap version currently included with GTSAM? Add more context in PR comment and req-request review?

**Comment by varunagrawal** [comment]
@dellaert added details on pickling with the wrapper.

**Review by dellaert — APPROVED** [review]
Not holding up this PR, but why do we have a separate pickle and serialize method? Is not every serializable class pickalable?

**Comment by varunagrawal** [comment]
It is. I noticed this exact problem when making this PR, but this requires a change to the wrapper. I can do it over the next week after higher priority items have been completed. :slightly_smiling_face:

**Pull request merged**
