### PR TITLE
Run all windows tests

### PR DESCRIPTION
**Pull request by talregev**
Run all windows tests
@varunagrawal Thank you for approve the windows fix PR. I am now able to run and show you all the tests are compile and 7 tests are failing. This PR is not aim to change anything. Just to show status of windows tests that need to be fix in the correctness. 
I didn't dive in gtsam lib. I had previous experience with gtsam, as I use it in my article. But long time I didn't use, and I am not familiar with everting is going on, and I don't have the knowledge to fix these tests.  
@varunagrawal Let me know what do you want to do about it. And if you want me to close this PR. 

Thank you for your help and your time.

### CODE REVIEW

**Comment by varunagrawal** [comment]
@talregev I don't understand. Why raise a PR if you don't intend to fix something?

**Comment by talregev** [comment]
> @talregev I don't understand. Why raise a PR if you don't intend to fix something?

I wanted to make forward to fix windows tests correctness if possible. Do you want that I will close this PR?

**Comment by varunagrawal** [comment]
What do you mean by "make forward to fix windows tests"? If you aren't trying to fix them, I don't see the point of raising this PR, especially since it is consuming limited CI resources.

**Comment by talregev** [comment]
> What do you mean by "make forward to fix windows tests"? If you aren't trying to fix them, I don't see the point of raising this PR, especially since it is consuming limited CI resources.

ok.

**Pull request closed without merging**
