### PR TITLE
TableFactor Improvements

### PR DESCRIPTION
**Pull request by varunagrawal**
- Adds a new constructor to the `TableFactor` which takes a `DiscreteConditional`. The API for the TableFactor should now mimic that of the `DecisionTreeFactor`.
- Move `cardinalities_` and `discreteKeys()` to the `DiscreteFactor` class to reduce code duplication.
- Renamed all "tree" based variables in hybrid elimination to names which are agnostic of the underlying factor type. **No change in functionality**.

### CODE REVIEW

**Comment by dellaert** [comment]
@varunagrawal this PR shows changes in 15 files, just for adding a constructor? Are you sure it targets the right branch?

**Comment by varunagrawal** [comment]
I need to update the PR comments. I also moved a lot of common functionality up to the DisreteFactor class to keep it DRY.

**Comment by dellaert** [comment]
> I need to update the PR comments. I also moved a lot of common functionality up to the DisreteFactor class to keep it DRY.

Hmm, yes, but TableFactor is a big change, and I'd rather review that in a separate PR if possible.

**Comment by varunagrawal** [comment]
I need to update the PR comments. I also moved a lot of common functionality up to the DisreteFactor class to keep it DRY.

**Comment by varunagrawal** [comment]
Using TableFactor in elimination will be a separate PR for sure.

**Comment by varunagrawal** [comment]
@dellaert I've updated the PR comment to better reflect the changes. Please note that there is no functionality change in hybrid elimination in this PR, only variable name changes.

**Comment by dellaert** [comment]
OK. Any reason this is not targeting develop?

**Comment by varunagrawal** [comment]
> OK. Any reason this is not targeting develop?

I chained PRs together since I wanted functionality from different PRs and was not getting review responses to unblock me.

**Pull request merged**
