### PR TITLE
Fix 32-bit unit test failures

### LINKED ISSUE #306: Failed test on 32bit architectures
## Description

One unit test fails to pass in `armhf`

```
186/234 Test #186: testQPSolver ...........................***Failed    0.04 sec
Not equal:
expected:
4.371875
actual:
290687824935850081763694373348985159914898047944127280960733468936086603046127808004981004843733268589327788990324383899071870077623672891177494692327651468166411650774643726713810200573276388989574637258303295240952023116603342313435955200.000000
/<<PKGBUILDDIR>>/gtsam_unstable/linear/tests/testQPSolver.cpp:330: Failure: "assert_equal(0.437187500e01,error_actual, 1e-7)" 
There were 1 failures 
```

## Steps to reproduce

1. Build and run tests on architectures != amd64.

## Expected behavior

All unit tests should pass! :-)

## Environment

See build logs in:
https://launchpad.net/~joseluisblancoc/+archive/ubuntu/gtsam-develop/+packages

Note that right now, tests can't run for `ppc64el` and `arm64`, but errors there seem to be related to limited RAM in the builders instead.

### LINKED ISSUE #308: Failed tests in 32bit builds (i386 on PPA build farm)
## Description

Failure 1: (this is a weird one, but must have an explanation ?)

```
130/234 Test #130: testAHRSFactor .........................***Failed    0.01 sec
not equal:
expected = [
	0, 0, 0;
 	0, 0, 0;
 	0, 0, 0
]
actual = [
	        -1.01,  -4.92831e-85, -5.82588e-280;
 	 -4.92831e-85, -2.30763e-169, -7.25981e-280;
 	-9.12492e-102,  3.40735e-171, -2.54655e-280
]
actual - expected = [
	        -1.01,  -4.92831e-85, -5.82588e-280;
 	 -4.92831e-85, -2.30763e-169, -7.25981e-280;
 	-9.12492e-102,  3.40735e-171, -2.54655e-280
]
/<<PKGBUILDDIR>>/gtsam/navigation/tests/testAHRSFactor.cpp:376: Failure: "assert_equal(expectedDelRdelBiasOmega, preintegrated.delRdelBiasOmega(), 1e-3)"
```

Failure 2: (this one can be fixed by just relaxing a bit the thresholds)

```
 30/234 Test  #30: testLine3 ..............................***Failed    0.01 sec
Not equal:
expected:

  A[1] = [
	       0        0  5.00001 -5.00001;
   	-7.07107 -7.07107        0        0
  ]
  b = [  0 -0 ]
  No noise model
actual:

  A[1] = [
	       0        0        5       -5;
   	-7.07107 -7.07107        0        0
  ]
  b = [  0 -0 ]
  No noise model
not equal:
expected = [
	       0,        0,  5.00001, -5.00001;
 	-7.07107, -7.07107,        0,        0
]
actual = [
	       0,        0,        5,       -5;
 	-7.07107, -7.07107,        0,        0
]
actual - expected = [
	           0,            0, -8.58159e-06,  8.58159e-06;
 	-6.97755e-07, -6.97755e-07,            0,            0
]
Mismatch in Jacobian 1 (base 1), as shown above
/<<PKGBUILDDIR>>/gtsam/geometry/tests/testLine3.cpp:149: Failure: "gtsam::internal::testFactorJacobians(name_, f, val, 1e-5, 1e-7)" 
There were 1 failures
```

## Steps to reproduce

1. Run the tests on 32bit Intel architecture. 

## Expected behavior

Tests should pass. 

## Environment

https://launchpad.net/~joseluisblancoc/+archive/ubuntu/gtsam-develop/+packages

### PR DESCRIPTION
**Pull request by jlblancoc**
Closes #308 
Closes #306 

Don't merge until [these PPA builds](https://launchpad.net/~joseluisblancoc/+archive/ubuntu/sandbox/+packages) end, to confirm that the test errors have been fixed.

Update: It can be merged now, PPA builds pass!

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/310)

### CODE REVIEW

**Comment by dellaert** [comment]
Seems to say
```
buildsPackage build summary
A total of 92 builds have been created for this PPA.

Completed builds
23 successful
69 failed
```

**Comment by jlblancoc** [comment]
Yes... it still fails, but now because of #306, will try to fix it too in this pr.

**Comment by jlblancoc** [comment]
PS: you have to click on a package version on the bottom, the click on one of the platform that fails, then buildlog to see all the details.

**Comment by dellaert** [comment]
@jlblancoc please delete the branch when you’re done with it. I just realized maybe you were using it to push more changes.

SymmetricBlockMatrkx is pretty core: wondering what other bugs were caused by this. Although, now that I think more about it, I’m wondering whether I pushed merge too fast: is the semantics of the constructor to deliver a zero matrix, or just an allocated one? Perhaps the bug was caused by code that incorrectly assumed it would get zeros...

**Comment by jlblancoc** [comment]
Branch deleted, no problem. 

I guess the "problem" here is that SymmetricBlockMatrix expects to get all its entries correctly initialized by its caller, and this QP code was NOT filling in some of the entries... (it was filled to zeros, apparently only by accidents that depends on the architecture and Eigen implementation).
Now, what to do at the API level: 
- If you prefer to DETECT non-filled entries, maybe the hessian could be initialized to quietNAN instead of zeros?
- Or, to keep it as is, with zeros to be "benevolent" with "user" errors, or even document that behavior so zeroes in information matrices don't need to be filled it and save some time.

Not sure what's better.

**Comment by dellaert** [comment]
I think we actually have a flag that enables the Nan behavior. I think perhaps in *debug* the flag should be on by default, and we fill everything with Nan, while in Release we just allocated. Comments?

**Comment by jlblancoc** [comment]
I'll think about this. There may be another way to fix the bug that doesn't mask possible future bugs due to uninitialized values...

**Comment by jlblancoc** [comment]
Definitively, I think you are right, Frank: it might be better NOT to initialize to zeros, since it has a cost (vs. leave uninitialized) that may be relevant when building **very large** graphs. And all just to "fix" apparently buggy code... Will come back with another PR.

**Pull request merged**
