### PR TITLE
relax unit test thresholds to fix 32bit issues

### PR DESCRIPTION
**Pull request by jlblancoc**
This will solve part of the pending issues in #1605  : 

(cc @dkogan )
> * i386 fails one of the first set of tests: it looks like it just barely misses some thresholds, so it's probably not a failure. But since it failed something in the first set, we don't know if any of the second set of tests would have failed

### CODE REVIEW

**Comment by varunagrawal** [comment]
Would it be wise to set the thresholds based on preprocessor flags indicating the architecture type?

If we have the flag `GTSAM_ARCH_TYPE`, we could check at compile time and set this accordingly. Just a suggestion.

**Review by ProfFan — APPROVED** [review]
@jlblancoc Before merging could you add a `constexpr if` check on the current architecture?

**Comment by jlblancoc** [comment]
Take a look at the patch now.

I checked that `i686-linux-gnu-g++` defines both preprocessor symbols. i386 is actually obsolete and only i686 will remain for a few years as a main Debian arch, but I added both just in case.

@varunagrawal The idea of a cmake-level architecture variable that maps into a macro seems good (I think that is what your proposal is about?), but if we are using it just here, maybe just the macros are the minimal solution...

**Comment by jlblancoc** [comment]
One CI task failed, but *I think* it's not related to this PR's changes... I have re-launched it.

**Comment by varunagrawal** [comment]
Awesome! Merged

**Pull request merged**
