### PR TITLE
Fix/iSAM2 #1101

### PR DESCRIPTION
**Pull request by ProfFan**
It appears that the fixes in #1172 is not merged to develop, we may need to solve the conflicts first though...

### CODE REVIEW

**Comment by dellaert** [comment]
Wow - totally forgot about this. Seems CI fails?

**Comment by ProfFan** [comment]
@dellaert

**Review by dellaert — APPROVED** [review]
Cool, many thanks !!! I will merge

**Comment by tanzby** [comment]
Dose 4.2 release include this PR? Those changes seems important for iSAM2 @dellaert

**Pull request merged**
