### PR TITLE
Upgraded to Eigen 3.4.0

### PR DESCRIPTION
**Pull request by dellaert**
This is a straight up replacement of Eigen. No changes to default version to use, no using any special features, although there are plenty: https://eigen.tuxfamily.org/index.php?title=3.4

Any of these changes I'll make in a follow-up PR after discussion.

### CODE REVIEW

**Comment by dellaert** [comment]
@ProfFan no idea why this fails. cmake and build work perfectly fine on my Mac with clang, and even Mac CIs seem to fail here.

**Comment by ProfFan** [comment]
Indeed you are missing one file

Did you use the release tarball or copied the folder from the Git repo? You need to use https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip

in order to have a portable Eigen release, the Git tag one is broken

**Comment by dellaert** [comment]
> Indeed you are missing one file
> 
> Did you use the release tarball or copied the folder from the Git repo? You need to use [gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip](https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip)
> 
> in order to have a portable Eigen release, the Git tag one is broken

Actually, it seems I *did* use the one you pointed to.

**Comment by dellaert** [comment]
I figured it out. I missed many files because of an issue with .gitignore on Mac :-/ Let's see what CI says.

**Review by ProfFan — APPROVED** [review]

**Pull request merged**
