### PR TITLE
Wrapper Update for GTSAM 4.3

### PR DESCRIPTION
**Pull request by varunagrawal**
076a5e3a9 Merge pull request #157 from borglab/upgrade
5e0caa63d fix matlab wrapper for std::optional
f4ea1c2fe update matlab.h and docs
de87ee0ff fix tests
06a16ce46 update matlab cmake script
0e84fa49c add boost serialization flag to wrapping script
4bb10411a use std pointers and make boost serialization optional
ec647385f clean up python wrapper more
a4da6a021 update tests
709b80d2f update python wrapper CMake
5b50739d6 update template files
bfc0bf57b update python wrapper to use only std and to optionally wrap serialization methods
de8c4153b remove use_boost arg from interface_parser
4dc835aec repurpose use_boost flag to use_boost_serialization

git-subtree-dir: wrap
git-subtree-split: 076a5e3a95e68f3900beee0d063322ec83e80ae3

### CODE REVIEW

**Comment by dellaert** [comment]
Could you add a change to the workflow to use -j1 not -j2 to compile on Linux to see whether that fixes the CI?

**Comment by dellaert** [comment]
@mattking-smith could you please try building the matlab wrapper in this branch and report back?

**Comment by ProfFan** [comment]
`/usr/bin/ld: final link failed: No space left on device` it seems to be unrelated to -j1. This error is caused by ld not able to generate the linked dynamic library due to storage constraint

**Comment by dellaert** [comment]
> `/usr/bin/ld: final link failed: No space left on device` it seems to be unrelated to -j1. This error is caused by ld not able to generate the linked dynamic library due to storage constraint

Yes, but these large linking processes bunch up on my machine as well, and sometimes I need to switch to -j1 to get past it. @varunagrawal please give it a try?

**Comment by dellaert** [comment]
OK, I made the change myself...

**Review by dellaert — APPROVED** [review]
Thanks !!!!!

**Pull request merged**
