### PR TITLE
Add Python CI

### PR DESCRIPTION
**Pull request by ProfFan**
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/224)

### CODE REVIEW

**Comment by dellaert** [comment]
python CI seems to fail. You might want to temporarily suspend all other CI in this PR so you can iterate more quickly, then re-enable when everything works.

**Comment by ProfFan** [comment]
@dellaert 
image

**Comment by dellaert** [comment]
So, I’m lost. is this building and doing CI on *bothu cython and python wrappers? 

Also: 
1) python 2.7 EOL warnings. Are we checking 2.7 rather than python 3?
2) these warnings have been going in on my Mac as well:
CMake Warning at /usr/local/lib/cmake/boost_timer-1.71.0/libboost_timer-variant-shared.cmake:59 (message):
922  Target Boost::timer already has an imported location

**Comment by ProfFan** [comment]
@dellaert 
1. I have changed the tests to build & test against Python 3.
2. I think these warnings are not introduced by the Python CI?

**Comment by ProfFan** [comment]
On the 2nd issue, see: https://stackoverflow.com/questions/58081084/target-boostlibrary-already-has-an-imported-location-link-errors

**Comment by ProfFan** [comment]
Ping @dellaert

**Comment by dellaert** [comment]
I'm still lost :-) is this building and doing CI on *both* cython and python wrappers? I don't see the answer in comments above.

**Comment by ProfFan** [comment]
This is the CI for the old wrapper, as we have discussed in #204 :)

**Pull request merged**
