### PR TITLE
Hybrid Elimination with Normalization Constant

### PR DESCRIPTION
**Pull request by varunagrawal**
- `FactorAndConstant::error`
- Improve docstrings.
- Add log of normalization constant.

### CODE REVIEW

**Comment by dellaert** [comment]
I have a few changes as well, not pushed yet, so we should chat… mostly in python.

**Comment by varunagrawal** [comment]
Sure thing. Mine's all in C++. I was pretty productive at Schiphol.

I'll be landing in ATL at 8 pm so might be too late until I get home. Tomorrow afternoon/evening maybe?

**Comment by varunagrawal** [comment]
@dellaert please let me know when I can merge this in. :)

**Review by dellaert — APPROVED** [review]
Fantastic

**Pull request merged**
