### PR TITLE
Bump version and switch Pose3 expmap default

### PR DESCRIPTION
**Pull request by ProfFan**
This PR will:
1. Bump version to 4.0.3
2. Switch default Pose3 expmap to full, and Rot3 to full, for consistency.

@dellaert @varunagrawal 

#412

### CODE REVIEW

**Comment by ProfFan** [comment]
After this PR we will merge current develop to `release/4.0.3`.

**Comment by ProfFan** [comment]
Also note that there will be one unit test failure in `AdaptAutoDiff`, which should be dealt with first before merging.

**Comment by dellaert** [comment]
> Also note that there will be one unit test failure in `AdaptAutoDiff`, which should be dealt with first before merging.

How/a add it to tracking issue... do you have a solution?

**Comment by ProfFan** [comment]
@dellaert  Because the `localCoordinates` of a `Camera` is a the (6+3=9) dim vector `<pose.local, cal.local>`, so after the expmap change the local coordinate of the pose difference changed (`P` in code). Because `P` changed, the result of Snavely also changed, thus the `#ifdef`s are required and correct.

Proof:
```python
>>> import gtsam as g
>>> import numpy as np
>>> p1=g.Pose3.Expmap(np.array([0.1, 0.2, 0.3, 0.7583528428, 4.9582357859, -0.224941471539]))
>>> r1=p1.rotation()
>>> g.Rot3.Logmap(r1)
array([0.1, 0.2, 0.3])
```

Quote:
```c++
namespace example {
Camera camera(Pose3(Rot3().retract(Vector3(0.1, 0.2, 0.3)), Point3(0, 5, 0)),
              Cal3Bundler0(1, 0, 0));
Point3 point(10, 0, -5);  // negative Z-axis convention of Snavely!
Vector9 P = Camera().localCoordinates(camera);
Vector3 X = point;
#ifdef GTSAM_POSE3_EXPMAP
Vector2 expectedMeasurement(1.3124675, 1.2057287);
#else
Vector2 expectedMeasurement(1.2431567, 1.2525694);
#endif
Matrix E1 = numericalDerivative21<Vector2, Vector9, Vector3>(adapted, P, X);
Matrix E2 = numericalDerivative22<Vector2, Vector9, Vector3>(adapted, P, X);
}

/* ************************************************************************* */
// Check that Local worked as expected
TEST(AdaptAutoDiff, Local) {
  using namespace example;
#ifdef GTSAM_POSE3_EXPMAP
  Vector9 expectedP = (Vector9() << 0.1, 0.2, 0.3, 0.7583528428, 4.9582357859, -0.224941471539, 1, 0, 0).finished();
#else
  Vector9 expectedP = (Vector9() << 0.1, 0.2, 0.3, 0, 5, 0, 1, 0, 0).finished();
#endif
  EXPECT(equal_with_abs_tol(expectedP, P));
  Vector3 expectedX(10, 0, -5);  // negative Z-axis convention of Snavely!
  EXPECT(equal_with_abs_tol(expectedX, X));
}
```

**Comment by ProfFan** [comment]
Since there is no objection, I will merge this and checkout 4.0.3 release :)

**Comment by dellaert** [comment]
> Since there is no objection, I will merge this and checkout 4.0.3 release :)

By "checkout" you mean merge in develop and release it?

**Comment by ProfFan** [comment]
@dellaert  Yes

**Pull request merged**
