### PR TITLE
[WIP] New Python Wrapper

### PR DESCRIPTION
**Pull request by ProfFan**
This giant pile of commits definitely needs to be cleaned up. Since this originates from a fork, we probably need to cherry-pick commits this time.

@matthewsklar We should meet in the coming week or so to figure this out :)

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/134)

### CODE REVIEW

**Comment by octopuscabbage** [comment]
Hi, We are planning to use the python API for a project. Do you know likely when this will be merged? Also does this wrap factors like the GPS factor or allow declaration of new factors in python? (We would like to use a GPS factor in our project) 

If this is an inappropriate place to ask this, I can delete this and ask somewhere else.

**Comment by dellaert** [comment]
This is a modernization of the existing wrapper. In theory you can already do python wrapping (with the cython wrapper machinery) of a project, but we are planning to add an example of that soon.

**Comment by dellaert** [comment]
Does this supersede PR #66 ?

**Comment by ProfFan** [comment]
@dellaert It should, but need confirmation.

**Comment by matthewsklar** [comment]
@dellaert It does

**Comment by ProfFan** [comment]
Closing in lieu of my branch

**Pull request closed without merging**
