### PR TITLE
test cases for IncrementalFixedLagSmoother

### PR DESCRIPTION
**Pull request by truher**
two cases here:

* SEGV while marginalizing a variable with only a prior.
* IndexError during marginalization that seems distantly caused by the behavior of update()?

### CODE REVIEW

**Comment by ProfFan** [comment]
Thanks! The `IncrementalFixedLagSmoother` has been known to have problems. There are several workarounds in the issues section, but none of us have the bandwidth for the bugfix right now.

**Comment by truher** [comment]
no worries, i appreciate your quick response.  i can avoid these particular issues, though i'm concerned that there may be more issues lurking in the future.  is there a better choice than `IncrementalFixedLagSmoother` ?  The "batch" version doesn't seem to have implemented the `marginalCovariance` method, which I kinda want.

**Comment by dellaert** [comment]
I appreciate the tests and might take a look. I have been seeing some other segfaults with 3.12.
What version of python are you using?

**Comment by truher** [comment]
thank you!  i know you're very busy.

re: python version, i'm using 3.10.12, on ubuntu 22.04.

**Comment by truher** [comment]
closed so i can have the "develop" branch back.

see https://github.com/borglab/gtsam/pull/1809

**Pull request closed without merging**
