### PR TITLE
Additional Nonlinear CG Direction Methods

### PR DESCRIPTION
**Pull request by varunagrawal**
Added other direction methods for CG beyond Polak-Ribiere.

### CODE REVIEW

**Comment by dellaert** [comment]
I’ll look at this after other PRs have been addressed.

**Comment by dellaert** [comment]
Could you also template these in the same vein as Polak-Ribiere? The idea -as I remember it-  is that CG does not need to know whether the underlying "system" is actually a dense, sparse, graph, or other system that has the right operators. I do regret that we did not add unit tests in that vein.

**Comment by varunagrawal** [comment]
> Could you also template these in the same vein as Polak-Ribiere? The idea -as I remember it- is that CG does not need to know whether the underlying "system" is actually a dense, sparse, graph, or other system that has the right operators. I do regret that we did not add unit tests in that vein.

Ah good catch. I'll do that right now.

**Comment by varunagrawal** [comment]
I still need to add some tests. Will do that later today.

**Review by dellaert — APPROVED** [review]
Cool!

**Pull request merged**
