### PR TITLE
Verdant/smart ptrs

### PR DESCRIPTION
**Pull request by kartikarcot**
This PR will replace all boost smart pointer usage with STL smart pointers.
* It is a simple find and replace of all boost smart ptr usage with stl
* Things that changed were:
   - `dynamic_pointer_cast`
   - `shared_ptr`
   - `weak_ptr`
   - `make_shared`
   - `allocate_shared`

### CODE REVIEW

**Comment by dellaert** [comment]
Okidoke. Remember to *merge* now that this branch is public. No force-push.

**Comment by dellaert** [comment]
Cool, LGTM if a straightforward replace. I will not check all 428 files.
Was there an impact involving boost allocators?
PS change away from WIP before I can merge.

**Review by dellaert — APPROVED** [review]
A landmark moment in GTSAM's history :-)

**Comment by dellaert** [comment]
Also, please confirm no changes were needed to wrap, except using the flag? As wrap is pulled in as a git sub-tree, any changes would have to made upstream...

**Comment by kartikarcot** [comment]
Forgot to revert the wrap changes. I will revert them

**Comment by kartikarcot** [comment]
I did not face issues with allocators. I did see Eigen and TBB allocators being used. I replaced `boost::allocate_shared`with `std::allocate_shared` but that did not cause any issues

**Comment by dellaert** [comment]
One failing CI is probably an OOM error. Will see what other gcc workflows do before merging.

**Comment by kartikarcot** [comment]
Can we re run this? Hopefully it's one-off

**Comment by kartikarcot** [comment]
```
g++-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [python/CMakeFiles/gtsam_py.dir/build.make:265: python/CMakeFiles/gtsam_py.dir/nonlinear.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:6939: python/CMakeFiles/gtsam_py.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Error: Process completed with exit code 2.
```
This definitely feels like compiler did not get enough memory

**Comment by dellaert** [comment]
Seems this OOM CI fail for gcc is systematic after this PR. Specifically, it is the python wrapper nonlinear.i that fails. To fix this, we could try a separate .i file for Values alone (heavily templated). @ProfFan @varunagrawal is that possible and do you agree with the diagnosis? It could just be something new in this PR that makes it trip, although Error 4 is OOM according to Google. Maybe there is some fix to give it more space?

**Pull request merged**
