### PR TITLE
Fix memory leak in Expressions

### PR DESCRIPTION
**Pull request by ProfFan**
There is a memory leak in expressions when the expression involves an object that is not functionally constructed (`StereoCamera` here in `testTriangulation.cpp`, which involves incrementing the reference count of a `shared_ptr` pointing to the `Cal3_S2Stereo` object).

Thus, each time `valueAndJacobianMap` is called, the RC is incremented, but never decreased because of a raw placement new in `ExpressionNode.h`:
```cpp
    // Create a Record in the memory pointed to by ptr
    // Calling the constructor will record the traces for all arguments
    // Write an Expression<A> execution trace in record->trace
    // Iff Constant or Leaf, this will not write to traceStorage, only to trace.
    // Iff the expression is functional, write all Records in traceStorage buffer
    // Return value of type T is recorded in record->value
    // NOTE(frank, abe): The destructor on this record is never called due to this placement new
    // Records must only contain statically sized objects!
    Record* record = new (ptr) Record(values, *expression1_, ptr);
```

I only ran this on the unit tests, could someone test it on a real demo or application? Thanks :)

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/373)

### CODE REVIEW

**Comment by dellaert** [comment]
Nice. Before I approve, could you add some evidence in this PR that there was a problem before and it is no longer a problem now? This provides Some validation and context but also information towards future possible issues.

**Comment by ProfFan** [comment]
Before
```cpp
gtsam/geometry/tests/testTriangulation
Counts: cameras[0] 9
There were no test failures

=================================================================
==502119==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7f19f2728f41 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55931872e666 in boost::detail::shared_count::shared_count<gtsam::Cal3_S2Stereo*, boost::detail::sp_ms_deleter<gtsam::Cal3_S2Stereo> >(gtsam::Cal3_S2Stereo*, boost::detail::sp_inplace_tag<boost::detail::sp_ms_deleter<gtsam::Cal3_S2Stereo> >) (/home/fan/Projects/CV/SLAM/gtsam_build/gtsam/geometry/tests/testTriangulation+0x22f666)
    #2 0x5593187220ac in boost::shared_ptr<gtsam::Cal3_S2Stereo>::shared_ptr<gtsam::Cal3_S2Stereo, boost::detail::sp_inplace_tag<boost::detail::sp_ms_deleter<gtsam::Cal3_S2Stereo> > >(gtsam::Cal3_S2Stereo*, boost::detail::sp_inplace_tag<boost::detail::sp_ms_deleter<gtsam::Cal3_S2Stereo> >) (/home/fan/Projects/CV/SLAM/gtsam_build/gtsam/geometry/tests/testTriangulation+0x2230ac)
    #3 0x559318713a5f in boost::detail::sp_if_not_array<gtsam::Cal3_S2Stereo>::type boost::make_shared<gtsam::Cal3_S2Stereo, double, double, int, double, double, double>(double&&, double&&, int&&, double&&, double&&, double&&) (/home/fan/Projects/CV/SLAM/gtsam_build/gtsam/geometry/tests/testTriangulation+0x214a5f)
    #4 0x5593186f0c0d in triangulationStereotriangulateNonlinearTest::run(TestResult&) /home/fan/Projects/CV/SLAM/gtsam/gtsam/geometry/tests/testTriangulation.cpp:339
    #5 0x55931882e0c0 in TestRegistry::run(TestResult&) /home/fan/Projects/CV/SLAM/gtsam/CppUnitLite/TestRegistry.cpp:62
    #6 0x55931882dd22 in TestRegistry::runAllTests(TestResult&) /home/fan/Projects/CV/SLAM/gtsam/CppUnitLite/TestRegistry.cpp:29
    #7 0x5593186f60e9 in main /home/fan/Projects/CV/SLAM/gtsam/gtsam/geometry/tests/testTriangulation.cpp:441
    #8 0x7f19eef86001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 1 allocation(s).
```

after:
```
gtsam/geometry/tests/testTriangulation
Counts: cameras[0] 9
There were no test failures
```

**Comment by ProfFan** [comment]
I think AppVeyor is somehow broken because of an update of VS version by them? @jlblancoc Could you help investigate this? Thanks a lot ;)

**Comment by ProfFan** [comment]
Confirmed exactly today AppVeyor pushed a new image for the CI: https://www.appveyor.com/updates/

I'll try finding a fix.

**Pull request merged**
