### PR TITLE
CMake Updates

### LINKED ISSUE #1478: Matlab wrapper cannot be compiled on M1 Mac
My computer is Macbook Pro 16inch with M1 pro. 
I am trying to install with Matlab wrapper by using the following command:
cmake  -DGTSAM_INSTALL_MATLAB_TOOLBOX=ON  ..

Matlab R2022b is installed in my Mac.

Error shown:
-- GTSAM Version: 4.3a0
-- GTSAM is a shared library due to BUILD_SHARED_LIBS is ON
-- GTSAM_POSE3_EXPMAP=ON, enabling GTSAM_ROT3_EXPMAP as well
-- Found Eigen version: 3.4.0
-- checking for thread-local storage - found
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_LIBRARIES) 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find TBB (missing: TBB_INCLUDE_DIRS TBB_LIBRARIES tbb tbbmalloc) (Required is at least version "4.4")
-- Building 3rdparty
-- Could NOT find GeographicLib (missing: GeographicLib_LIBRARY_DIRS GeographicLib_LIBRARIES GeographicLib_INCLUDE_DIRS) 
-- Building base
-- Building basis
-- Building geometry
-- Building inference
-- Building symbolic
-- Building discrete
-- Building hybrid
-- Building linear
-- Building nonlinear
-- Building sam
-- Building sfm
-- Building slam
-- Building navigation
-- GTSAM Version: 4.3.0
-- Install prefix: /usr/local
-- Building GTSAM - as a SHARED library
-- Building base_unstable
-- Building geometry_unstable
-- Building linear_unstable
-- Building discrete_unstable
-- Building dynamics_unstable
-- Building nonlinear_unstable
-- Building slam_unstable
-- Building partition_unstable
-- GTSAM_UNSTABLE Version: 4.3.0
-- Install prefix: /usr/local
-- gtwrap Package config : /usr/local/lib/cmake/gtwrap
-- gtwrap version        : 1.0
-- gtwrap CMake path     : /usr/local/lib/cmake/gtwrap
-- gtwrap library path   : /usr/local/lib/gtwrap
-- gtwrap binary path    : /usr/local/bin/gtwrap
-- gtwrap header path    : /usr/local/include/gtwrap
CMake Error at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Matlab (missing: Matlab_MEX_LIBRARY Matlab_MX_LIBRARY
  MEX_COMPILER) (found version "9.13")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindMatlab.cmake:2038 (find_package_handle_standard_args)
  wrap/cmake/MatlabWrap.cmake:10 (find_package)
  wrap/cmake/MatlabWrap.cmake:67 (find_and_configure_matlab)
  matlab/CMakeLists.txt:85 (matlab_wrap)

Can you help me out? Thanks in advance

### PR DESCRIPTION
**Pull request by varunagrawal**
1. Support for Apple silicon.
2. Added flag `GTSAM_ENABLE_MEMORY_SANITIZER` to allow for running `libsanitizer`.

Fixes #1478 & #1499.

Tagging @berndpfrommer so he can pitch in too!

### CODE REVIEW

**Comment by berndpfrommer** [comment]
Thanks for adding the libsanitizer feature! Would love to test but I'm currently traveling with very limited connectivity. Should get back to civilization before weekend.

**Comment by jlblancoc** [comment]
Awesome, thanks for catching up on this! 
LGTM, just adding those flags should work. I haven't tested it, though, assuming you tested it before PR :-)

**Review by jlblancoc — APPROVED** [review]
My only comment is that it *might* make sense to also add the thread sanitizer option, but only if gtsam explicitly uses multithreading... I think it does through TBB only. Even though, it might be a good future addition (e.g. "GTSAM_ENABLE_THREAD_SANITIZER").

Also, these new options only work in GCC. We can assume only advanced users will enable it so no warnings are required (?).

**Comment by varunagrawal** [comment]
Okay updated the test. I believe this flag will be used by those more familiar with the build system and GCC so a warning may not be necessary. If people start to raise issues, I can go back and add the warning in a future PR, maybe even in the thread sanitizer PR.

Also, if this doesn't work in non-default builds, we can look more closely at that later as well. :)

I'll merge this once CI passes.

**Pull request merged**
