### PR TITLE
Fix the race!

### PR DESCRIPTION
**Pull request by ProfFan**
This fixes the TBB race by adding proper locks.

### CODE REVIEW

**Comment by ProfFan** [comment]
This fixes #1092. @DanMcGann @acxz @cdb0y511 @matlabbe could you all take a look and see if this fixed your problem?

**Comment by varunagrawal** [comment]
Can we get some performance numbers please?
Want to make sure the mutexes aren't preventing full parallelization.

**Comment by ProfFan** [comment]
I did tracing locally, the lock is only hit about 5 times per optimization and the performance impact is neglectable. @varunagrawal

**Comment by varunagrawal** [comment]
Having full performance metrics would still be great. Think about when something changes in the future and someone else comes and looks at this PR.

**Comment by ProfFan** [comment]
Before: 1.33s per optimization
After: 1.35s per optimization for the benchmark `testTBBFail` posted in `fix/tbb_regression` (experiment branch)

**Comment by ProfFan** [comment]
@dellaert It would be great if this can be merged before 4.2a6, since this is very important for TBB to be actually used in practice.

**Comment by ProfFan** [comment]
Thanks Varun!

**Comment by dellaert** [comment]
Please note 4.2a6 is already set in stone: Linux wheels have been out. We can't have 2 different 4.2a6 versions!
Waiting for Fan to create mac wheels and upload them to pypi.

**Pull request merged**
