### PR TITLE
Fix windows tests

### PR DESCRIPTION
**Pull request by talregev**
My commits above yours give better results:
1. Add fix for compilation in Visual Studio. This seems to be a weird issue with how size_t is interpreted since the multiple symbols defined error comes from additional declarations of std::map<Key, size_t>. This might be a bug in MSVC 16.
2. Fixed some more tests across the repo.
3. Updated the Windows CI to run additional GTSAM tests as well as some gtsam_unstable tests.
4. Compile with ninja
5. GTSAM_EXPORT on functions.
6. GTSAM_EXPORT on nested structs / classes.

### CODE REVIEW

**Comment by talregev** [comment]
@varunagrawal If you can approve the ci it will be great.
You can also look on the CI on my repo:
https://github.com/talregev/gtsam/pull/8

**Comment by talregev** [comment]
image

**Comment by varunagrawal** [comment]
Why not checkout my fix branch, make a branch off that and then target this PR to my branch? That will make the history clean and avoid duplication.

**Comment by talregev** [comment]
> Why not checkout my fix branch, make a branch off that and then target this PR to my branch? That will make the history clean and avoid duplication.

Because it has conflict with develop when I do that.

**Comment by varunagrawal** [comment]
> > Why not checkout my fix branch, make a branch off that and then target this PR to my branch? That will make the history clean and avoid duplication.
> 
> Because it has conflict with develop when I do that. I solve also the conflict.

Go ahead and do that. I'll resolve the conflict with develop on my branch when we merge this to #1553.

**Comment by talregev** [comment]
I guess I have more problems.

**Comment by varunagrawal** [comment]
Okay wait I am resolving this here.

**Comment by varunagrawal** [comment]
@talregev you should now be able to push to this PR without problems.

**Comment by talregev** [comment]
@varunagrawal 
Thank you for your merge, I hope it will not effect the solution. 
 
I want to add: 
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```
To all workflows. 
This code mean that every time I push a commit to my PR, the other check will cancel immediately and the runner (vm machine) will available for the next push. (This include any other person that open a PR).
This make more rapid checks for the PRs.

**Comment by varunagrawal** [comment]
I love that idea! Also add a comment in the workflow file explaining that how you did over here. It is very useful!

**Comment by talregev** [comment]
@varunagrawal Please approve again my CI :)

**Comment by talregev** [comment]
It will affect on my next push.

**Comment by talregev** [comment]
@varunagrawal Can you cancel the runner on previous commit? It will take forever until it start running on the new commit. 
Because I added the new code, only on the new commits, the runner will cancel automatic.

**Comment by talregev** [comment]
The selected ones:

image

**Comment by talregev** [comment]
@varunagrawal I am done working on this branch.
There is `one or more multiply defined symbols found` errors that I don't know to solve for now.
Can you merge this branch to your windows fix and start play there? 
Once you solve these errors, I will continue to open the rest of the tests and solve the other issue of linkages. 
I will create a new branch and a new PR from your `fix/windows-tests` branch after the merge.

Thank you for your help.

**Pull request merged**
