### PR TITLE
rolling shutter projection factor

### PR DESCRIPTION
**Pull request by shteren1**
Hi @dellaert as promised here is a PR for the rolling shutter projection factor you helped me write.
I'm sorry it contains on unit tests, unfortunately i'm mainly a python developer and i have very little experience with working with cpp code (I'm also sorry if my cpp coding is a bit messy).

I don't know how to compile and run the unit tests in cpp, my use case was always compiling gtsam with python wrappers and using gtsam from python.

I did use this factor a lot running SLAM from calibrated monocular rolling shutter camera on many data sets and it works well.

### CODE REVIEW

**Review by dellaert — CHANGES_REQUESTED** [review]
Awesome!!! But without unit tests we cannot merge this. If you have unit tests in python, then please check those in?

**Comment by shteren1** [comment]
yes I will add python test, also I'll try to see why it failed to compile, perhaps my clone of gtsam is slightly older and some pieces of code changed.

**Comment by ProfFan** [comment]
Ping @shteren1

**Comment by shteren1** [comment]
@ProfFan sorry i've been really busy lately, i will get to it.

**Comment by lucacarlone** [comment]
@shteren1 @dellaert : I'm planning to implement a smart projection factor for rolling shutter measurements as well. @shteren1: If you want, merge this fork into feature/rollingShutterSmartFactors and I'll make it compile and add unit tests on my side (I'll need to do that for my factor anyways).

**Comment by shteren1** [comment]
@lucacarlone  that would be great! have you looked at my branch? did you figure out what I did here?

**Comment by lucacarlone** [comment]
> @lucacarlone that would be great! have you looked at my branch? did you figure out what I did here?
> 
> PR created: #826

excellent! yes, I read your code and looks great. I already have a test for the interpolation Jacobians and will work on the rest in the next few days. I'll keep you posted!

**Pull request merged**
