### PR TITLE
Optional jacobian computation in PreintegrationBase predict function

### PR DESCRIPTION
**Pull request by varunagrawal**
Speed up of `predict` in `PreintegrationBase.cpp` by asking for jacobians for `predict_state` and `predict_delta` optionally.

Also removed the TODO since `testIMUFactor.cpp` has tests for correctness.

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/323)

### CODE REVIEW

**Comment by mikesheffler** [comment]
> 
> 
> That should result in a nice speedup for anyone using predict.

Guess who's got two thumbs and uses `predict`? THIS GUY. 😄 Excited to see this roll out.

**Comment by dellaert** [comment]
@mikesheffler would be nice if you could validate that there is indeed a speedup :-) We just saw this small optimization as were were looking through the code in advance of using it. We have not actually  used it yet in this new project!

**Comment by mikesheffler** [comment]
> 
> 
> @mikesheffler would be nice if you could validate that there is indeed a speedup :-) 

The codebase I would use is on a machine that I can't reach via VPN (have to physically go in to the office, which I will probably do in the next few days), but, let me see if I have something on a machine I can reach. If I do, I will give it a try and report back!

**Comment by mikesheffler** [comment]
Btw, Could one of you point me toward a good example of some code in the repo doing this basic sort of timing? There are lots of ways to run a timer, but I may as well do it the preferred way, if such a way exists.

**Comment by dellaert** [comment]
Anything time*.cpp
Good example would use timing.h

**Comment by varunagrawal** [comment]
Recommendation to use the `std::chrono` library. It takes care of a lot of the unnecessary hassles.

**Comment by dellaert** [comment]
> Recommendation to use the `std::chrono` library. It takes care of a lot of the unnecessary hassles.

My recommendation to use timing.h stands... If we don't use chrono in there (we might!) feel free to PR

**Comment by varunagrawal** [comment]
> > Recommendation to use the `std::chrono` library. It takes care of a lot of the unnecessary hassles.
> 
> My recommendation to use timing.h stands... If we don't use chrono in there (we might!) feel free to PR

I mentioned `std::chrono` before I saw your comment on `timing.h` (guess github didn't refresh in time). From what I've seen, `timing.h` uses Boost timers and optionally TBB timers if TBB is available.

**Comment by mikesheffler** [comment]
**Short:** It's faster. By a lot. Nice job, @varunagrawal 

**Longer:** 

I won't be able to get on my computer I use for this stuff for a little while, but I did a quick test in a VM. I modified `ImuFactorsExample.cpp` (it uses `predict`) to include timing tests, by wrapping the call to `predict` in `gttic_(Predict)` and `gttoc_(Predict)` with the toc call being followed by `tictoc_finishedIteration();` and, finally, `tictoc_print_();` being called at the end.

The call to `predict` doesn't happen nearly enough with that dataset (only 100 times), so I created a loop wherein I assigned the output of predict to a dummy variable and did so 1 million times. So, with the 100 times the loop is called, that should be 100 million calls to `predict`.

Over several runs, the average without the change was 27.03 seconds (this is the first number reported by `tictoc_print()` -- it's stated as `27.xx CPU`). The average _with_ the change was 15.48 seconds.

So, that's a pretty substantial change. There's a lot of asterisks (virtual machine, tight loop, not a lot of power in the statistics ....), but I'm at least confident in saying it's clearly beneficial 😄

**Comment by dellaert** [comment]
That's awesome. Will merge !

**Comment by varunagrawal** [comment]
Nice!!! Thank you for the analysis @mikesheffler

**Pull request merged**
