### PR TITLE
Fix (issue #1336) dangling pointer access violation.

### PR DESCRIPTION
**Pull request by oicchris**
Fixes (#1336) a dangling pointer access violation when Expression<>::valueAndJacobianMap() is called using a MSVC compiler.  Deallocation of the pointer occurs before internal::ExecutionTrace<T> trace's dtor is called.  Inside the dtor the dangling pointer is dereferenced.

On a side note, I'm wondering why I was able to execute the unpatched code in Release.  I only encountered this issue when I ran in Debug.  Is it possible that the legal checks get "optimized" out in Release?  I'm guessing not because that'd be scary and reminiscent of the old Win9x days.

### CODE REVIEW

**Review by varunagrawal — APPROVED** [review]
LGTM.

Regarding Debug vs Release, that's interesting. Unfortunately, not a lot of us use Windows for GTSAM so at least I don't have the expertise there.

**Comment by dellaert** [comment]
Asserts are only run in Debug mode. We recommend developing code in Debug mode then switch to Release for ops.

**Comment by oicchris** [comment]
Hmm I wonder if I forked at a bad commit.  Let me update/merge and I'll re-up my PR.

**Review by varunagrawal — APPROVED** [review]

**Review by dellaert — APPROVED** [review]
If CI passes with this, all for it. After that, you might also want to squash and PR to `release/4.2` if you're up for that. I would wait to cut the 4.2 release if you tell me you'll do that.

**Comment by oicchris** [comment]
Weird, some Ubuntu Python debug-only builds are failing and the error messages aren't forthcoming.  In any case, I'm new to github and not sure the correct workflow to do as you asked.  In my organization's git, we have the process simplified to cherry pick the changes into the Release branch.  If it is simply to fork the release/4.2 branch and apply the changes, along with a commit log reference to the develop branch commit, I could do that.  Please advise, thank you!

**Comment by oicchris** [comment]
I did a search on the line: "g++-7: internal compiler error: Killed (program cc1plus)".  According to [this stackoverflow](https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus), it is possible that the CI is running out of memory.  However, some diagnostics might be needed, like the 'dmesg' utility mentioned in the article.  Do you have more information on the actual cause of the error?

**Comment by oicchris** [comment]
Ahh, it appears that this issue is not isolated to my commit, eg. PR #1410.  Perhaps I shouldn't have based this fix off of the develop branch?  Should I fork `release/4.2` to apply the fix an present a PR?

**Comment by dellaert** [comment]
I really think it's just an OOM issue - my colleague Kartik was able to compile and run the gcc CI locally.

**Comment by dellaert** [comment]
thanks @oicchris ! Since you already forked, you should just check out the release/2.4 branch and “cherry-pick” your commits above. You can then do a second PR, making sure the target is the release/2.4 branch.

**Pull request merged**
