### PR TITLE
Tiny Updates to Python Wrapper

### PR DESCRIPTION
**Pull request by contagon**
While using gtsam, I just ran into a handful of functions that hadn't been added to the python wrapper. They're all fairly straightforward and worked out of the box as you'd expect. I figured others may have use for them too.

Let me know if there's any questions/issues with any of them though.

### CODE REVIEW

**Comment by ProfFan** [comment]
Seems our Windows CI is broken, we need to fix that first before merging this PR

**Comment by ProfFan** [comment]
Hi @contagon could you merge master so the CI could run?

**Comment by contagon** [comment]
Just merged develop, let me know if that didn't do the trick.

**Review by dellaert — APPROVED** [review]
Very cool. I restarted a CI run that aborted, we can merge after tat. Thanks for this !

**Comment by dellaert** [comment]
@ProfFan any idea as to why that Python CI keeps breaking? It also does not pass on my PR from yesterday.

**Comment by ProfFan** [comment]
@dellaert I think it's GH Actions using the ephemeral cloud runners that got killed. You just need to manually restart the tasks that were stuck...

**Comment by varunagrawal** [comment]
@ProfFan I am currently having issues with the Python CI failing on a segfault on Windows. Could something in this PR inadvertently be causing the issue?

**Comment by varunagrawal** [comment]
Nevermind, I reverted the develop branch changes in my PR and the issue is still there. Seems like this might be a Windows+Python issue.

**Pull request merged**
