### PR TITLE
Fix can be marked override warning

### PR DESCRIPTION
**Pull request by ToniRV**

### CODE REVIEW

**Comment by ToniRV** [comment]
@varunagrawal, you were faster than I was to fix the `override` warning :smile: 
https://github.com/borglab/gtsam/commit/f831bfd62ec56373677c52ea5e035f2816451de0

Btw @varunagrawal, I thought that it'll be better to just fix all of those warnings at once...
Maybe it's a bit too much for a single PR, but I'll soon push a commit with all the fixes once `clang-tidy` finishes that should fix all these `virtual` vs `override` warnings.

Feel free to ignore it or merge it!

**Comment by ToniRV** [comment]
Ok, here it is! Feel free to add or ignore :) 
It is the cleanest way I know to modernize the code.

**Review by dellaert — APPROVED** [review]
Cool!!!!

**Comment by dellaert** [comment]
@varunagrawal or anyone that gets to it before me, feel free to merge after CI passes. Thanks Toni!

**Pull request merged**
