### PR TITLE
Verdant/boost serialization

### PR DESCRIPTION
**Pull request by kartikarcot**
This PR introduces a new flag to disable boost serialization functionality. Another move towards being able to build GTSAM without boost. Implemented this mainly through a compile time definition that conditionally deactivates all references to boost serialization.

Question for the reviewers:
- Where should this flag be placed? I chose to put it in the main CMakelists.txt

Note:
If you see some code changes in the diff that don't seem to be part of this PR, it's because it has changes from another branch (`feature/remove_boost_in_Values`) and will go away when that branch gets merged, which will happen before this will go in.

### CODE REVIEW

**Comment by dellaert** [comment]
@ProfFan tagged you for review and advice. We might do another PR down the line with your help to include "cereal", but this one at least allows compilation without boost for the most part. After this PR, I envision only one or more two PRs are needed to make that happen.

**Comment by dellaert** [comment]
CI fails, and somehow the diff did not update. I'd recommend (a) merging in develop again, and (b) - before pushing- figuring out what is killing the CI.

**Comment by ProfFan** [comment]
```
CMake Error at cmake/GtsamTesting.cmake:216 (add_executable):
[62](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:63)
  add_executable cannot create target "check_discrete_program" because
[63](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:64)
  another target with the same name already exists.  The existing target is
[64](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:65)
  an executable created in source directory
[65](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:66)
  "/home/runner/work/gtsam/gtsam/gtsam/base/tests".  See documentation for
[66](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:67)
  policy CMP0002 for more details.
[67](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:68)
Call Stack (most recent call first):
[68](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:69)
  cmake/GtsamTesting.cmake:30 (gtsamAddTestsGlob_impl)
[69](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:70)
  gtsam/geometry/tests/CMakeLists.txt:9 (gtsamAddTestsGlob)
[70](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:71)

[71](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:72)

[72](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:73)
CMake Error at cmake/GtsamTesting.cmake:217 (target_link_libraries):
[73](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:74)
  Attempt to add link library "CppUnitLite" to target
[74](https://github.com/borglab/gtsam/actions/runs/3984064957/jobs/6829916408#step:5:75)
  "check_discrete_program" which is not built in this directory.
```

**Comment by kartikarcot** [comment]
That's weird I don't remember modifying GtsamTesting.cmake

**Comment by kartikarcot** [comment]
But I did change the files that called it :)

**Review by dellaert — APPROVED** [review]
LGTM !!!

**Pull request merged**
