### PR TITLE
Fix for matlab wrapper in sfm.i

### PR DESCRIPTION
**Pull request by akshay-krishnan**
Changes from pair<size_t, size_t> to IndexPair

### CODE REVIEW

**Comment by akshay-krishnan** [comment]
@varunagrawal would this fix the matlab wrapper? I don't have matlab myself, so wont be able to test it.

**Comment by johnwlambert** [comment]
Thanks Akshay. Looks fine to me, but I'll defer to the CI and to anyone with a MATLAB license...

I don't understand why this change is necessary, though : - ) [IndexPair](https://github.com/borglab/gtsam/blob/develop/gtsam/base/DSFMap.h#L117) should compile to a pair of size_t's, looking at its definition:
```c++
class IndexPair : public std::pair<size_t,size_t> {
```

**Comment by varunagrawal** [comment]
@akshay-krishnan compiles great.

@johnwlambert this seems to be something going on at the compiler level and my guess is it has to do with template matching at compile time. You're specifying the template as `IndexPair` but using `std::pair<size_t, size_t>` so perhaps the match is incorrect?

**Comment by akshay-krishnan** [comment]
Thanks! We can merge once CI completes.

**Pull request merged**
