### PR TITLE
Fix LLVM repo keys

### PR DESCRIPTION
**Pull request by ProfFan**
This should fix the problem in https://github.com/borglab/gtsam/pull/556/checks?check_run_id=1234393111

### CODE REVIEW

**Comment by ProfFan** [comment]
@johnwlambert Please review this :)

**Comment by johnwlambert** [comment]
Looks good, thanks @ProfFan for adding this fix.

Would you mind adding a few more inline comments before we merge, just to increase the readability? Perhaps something like
```python
# We need to use a keyserver because.... we use this keyserver because...
# matrix.version 9 represents ...
# 15CF4D18AF4F7421 is the hash for ...
if [ "${{ matrix.compiler }}" = "clang" ] && [ "${{ matrix.version }}" = "9" ]; then
            gpg --keyserver pool.sks-keyservers.net --recv-key 15CF4D18AF4F7421
            gpg -a --export 15CF4D18AF4F7421 | sudo apt-key add -
```

**Comment by ProfFan** [comment]
I think as this is under clang if it's pretty self-explanatory...

**Comment by dellaert** [comment]
> I think as this is under clang if it's pretty self-explanatory...

Please be responsive to the reviewer's comment, rather than dismissive.

**Review by dellaert — CHANGES_REQUESTED** [review]
Please implement John's comment

**Comment by ProfFan** [comment]
@johnwlambert @dellaert done

**Review by johnwlambert — APPROVED** [review]

**Comment by ProfFan** [comment]
@dellaert Please accept :)

**Comment by dellaert** [comment]
> @dellaert Please accept :)

Did you actually read John’s comment? Maybe I’m just missing where you explain why we need a key server etc as he asked…

**Comment by johnwlambert** [comment]
Hi Fan, we need this to merge the SFM Example BAL updates, I think a brief comment about why we needed the keyserver would help. You could also consider making that hash key a bash variable, so that is a bit easier to read

**Comment by ProfFan** [comment]
@dellaert I think I have addressed @johnwlambert 's comments, could you approve this PR so we can merge?

**Review by dellaert — APPROVED** [review]

**Pull request merged**
