### PR TITLE
Support msvc 2022 along 2019

### LINKED ISSUE #1642: Building fails in VS22 due to ambiguous call
## Description

When building i get the following error message: 
```

Error C2668:	'gtsam::CameraSet<CAMERA>::SchurComplement': ambiguous call to overloaded function	ISAM2Example_SmartFactor	C:\cpp\libs\gtsam\gtsam\geometry	C:\cpp\libs\gtsam\gtsam\geometry\CameraSet.h	379	
```
## Steps to reproduce

1. clone repository
2. Choose Generator: Visual Studio 17 2022 with x64
3. Press configure and generate
4. Press Open Project
5. build ALL_BUILD

Then I get 6 error messages all related to ``` 'gtsam::CameraSet<CAMERA>::SchurComplement': ambiguous call to overloaded function```

These error messages comes from:
1. ISAM2Example_SmartFactor
2. SFMExample_SmartFactor
3. SFMExample_SmartFactorPCG
## Expected behavior

I expected gtsam to build.
I got it to build when unchecking GTSAM_BUILD_EXAMPLES_ALWAYS and GTSAM_BUILD_UNSTABLE, but it doesn't fix the underlying issue.

## Environment

Windows 10 x64
Visual Studio 17 2022
Boost 1.82
Cmake 3.26

### PR DESCRIPTION
**Pull request by talregev**
Fix #1642 
Support msvc 2022 along 2019:
- Change to toolset: 14.38
- Fix ambiguous call to overloaded function CameraSet.h(331)

### CODE REVIEW

**Comment by varunagrawal** [comment]
I thought you had fixed the hanging CI issue?

**Comment by talregev** [comment]
> I thought you had fixed the hanging CI issue?

I say probably will fix.
After my change The ci is much less to hang.
It was everytime, and now once for a while. So it improvement.
Also this PR is not about CI hanging.

**Comment by varunagrawal** [comment]
That's not quite what you said here: https://github.com/borglab/gtsam/pull/1714#issuecomment-1895975000

Again, please don't make claims without evidence. I have less reason to trust your changes now.

**Comment by talregev** [comment]
As you can see from my first msg on the PR:
https://github.com/borglab/gtsam/pull/1714#issue-2085908409

> Remove swap from python ci
It not needed for the ci.
Also may fix the hang problem.

Also you can see from other recent PRs here on gtsam that they are green and not red as they used to be. 

You don't have to trust on my good changes. You can test them as long as you want.

And if this was bad change you already would reverted my change without talking to me, as you write on the PR.

**Comment by talregev** [comment]
https://github.com/borglab/gtsam/pull/1714#issue-2085908409

On this comment I was talking about the swap that is not needed, because I show you how gcc not crash lacking the memory. 
Hang problem happened on tests and not on compilation, It a known problem of the ci, and the side effect of the swap is amplify this problem.

**Comment by varunagrawal** [comment]
The other PRs are green because I've been re-running the CI until the test passes. I also have not reverted your changes, I don't understand why you're accusing me of that.

**Comment by talregev** [comment]
I don't accused you that you reverted my changes.
You would have if it was a bad change (Sorry about my bad grammar).
I just say It a good change, that you can run again the ci and make it green, because it happens once in awhile. Before the change it happens more. Almost every time.
And as I try to explain that the remove the swap was connected to gcc memory allocation when compiling. And the ci is hang on tests.
So you connect the memory issue to the ci hang, and all I am saying the swap ci amplify this problem.
Do you think that the is hang because of memory on the tests?
Also you say that you don't trust my changes and still benefits from them.
So I am not sure what are you trying to achieve by saying that, or keep discuss on non releted pr of that problem.
If you think my changes is not good (the remove of the swap)
You can revert the change (not recommended)
or Open a new issue about ci hang or remove swap and write me there.

And if you can please review this PR.

**Review by varunagrawal — APPROVED** [review]

**Pull request merged**
