### PR TITLE
Added Spectra 0.9.0 to 3rdparty

### PR DESCRIPTION
**Pull request by dellaert**
Adding Spectra Eigenvalue solver for Shonan Averaging certificate

### CODE REVIEW

**Comment by varunagrawal** [comment]
Just a suggestion (no need to accept it :) ), would git submodules be a better way to add 3rd party modules? You get finer control of the version included and it is very easy to update the version via git.

**Comment by jlblancoc** [comment]
I will delay reviewing the PR until Frank gives his opinion on using submodules. Indeed, it's a much cleaner way to keep dependencies around. The main caveats are: (1) having to update the git clone instructions; and (2) dealing with users complaining if they didn't read the instructions... :-)

PS: @dellaert congrats of this awesome paper! ;-)

**Comment by dellaert** [comment]
Thanks @jlblancoc 
We can start doing this in 4.1 but I'd like to postpone and release Shonan code in 4.0.4

**Comment by dellaert** [comment]
main caveats are: (1) having to update the git clone instructions; and (2) dealing with users complaining if they didn't read the instructions... :-)

Indeed, 2 is a big issue

**Comment by ProfFan** [comment]
@dellaert  I have started to feel that too, although I introduced the wrap submodule in the pybind branch. I now think probably a monorepo is a better choice for users...

**Pull request merged**
