### PR TITLE
update calls from boost timer

### LINKED ISSUE #302: Deprecated Boost Timer Headers
## Description

Some files use a deprecated API to the Boost Timer library.

## Steps to reproduce

1. git clone https://github.com/borglab/gtsam
2. mkdir build && cd build && cmake .. && make && make all && make check && make timing

```
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam_unstable/partition/FindSeparator-inl.h:18,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam_unstable/partition/tests/testFindSeparator.cpp:16:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/discrete/tests/testAlgebraicDecisionTree.cpp:27:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
[ 59%] Linking CXX executable testAlgebraicDecisionTree
[ 59%] Built target testAlgebraicDecisionTree
Scanning dependencies of target testDecisionTree
[ 59%] Building CXX object gtsam/discrete/tests/CMakeFiles/testDecisionTree.dir/testDecisionTree.cpp.o
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/discrete/tests/testDecisionTree.cpp:20:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
                                                         ^
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/timing/timeMatrixOps.cpp:20:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/timing/timeMatrix.cpp:19:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:20,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam_unstable/timing/timeDSFvariants.cpp:23:
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

## Expected behavior

No deprecation warnings.

## Environment

OS: Arch Linux
GCC: 9.3.0
Boost: 1.72

## Additional information

The new header is be available from boost version 1.48 and onwards. See: https://www.boost.org/doc/libs/1_48_0/libs/timer/doc/cpu_timers.html

Another description of the newer API: https://theboostcpplibraries.com/boost.timer#ex.timer_01

Description of old API (Boost v1.47): https://www.boost.org/doc/libs/1_47_0/libs/timer/timer.htm

### PR DESCRIPTION
**Pull request by acxz**
Resolves #302 

I have changed the API however there is still one more thing to do. The `elapsed()` function in the old API gave CPU time in seconds, while in the newer version it returns a tuple of times in nanoseconds. I have updated the code to get the CPU time (user + system time) but have not done the conversion to seconds, yet.

The code does compile and run, but the times that get shown are off.

The oldest LTS Ubuntu ships with Boost 1.58 and the deprecation was added in Boost 1.48 so no supported systems should break with this change.

Wanted to submit a draft in case I don't get around to it so that someone else can pick it up.

---
This change is [Reviewable](https://reviewable.io/reviews/borglab/gtsam/303)

### CODE REVIEW

**Comment by dellaert** [comment]
We have this gtsam/timing stuff. Did you look at using that instead of boost? IF we do that then we only have to change timing.h whenever boost is updated.

**Comment by acxz** [comment]
hmm yes that would be a more elegant solution

**Comment by acxz** [comment]
Yeah I was looking at how to change the current timing code to use timing.h. I think it'll work, I'll ping u guys when I'm ready with this later this weekend.

**Comment by acxz** [comment]
@dellaert okay it should be good now. I checked the times before and after and they all match up.

**Comment by dellaert** [comment]
Awesomesauce! travis timed out but I restarted the build

**Comment by acxz** [comment]
Great, seems like the CI has finished now.

**Pull request merged**
