### PR TITLE
Update LieGroups.lyx

### PR DESCRIPTION
**Pull request by melhashash**
Fix typo in the equation in item 1 section 5.3

### CODE REVIEW

**Review by mikesheffler — COMMENTED** [review]
Pretty sure this is correct. I don't think the corresponding .pdf is automatically generated (note that it is present in the source tree), so I don't want to approve it yet.

Should @melhashash generate a .pdf, or does someone in particular create it?

**Comment by dellaert** [comment]
I think this is right. I'll approve but if you can render  the PDF that would be better. I'll wait to merge until I heard from you.

**Review by dellaert — APPROVED** [review]

**Comment by melhashash** [comment]
I have generated the pdf. 

Note: the font has changed, and references are added at the end (it was missing in the original document).

@dellaert @mikesheffler

**Comment by dellaert** [comment]
Awesome, thanks !

**Pull request merged**
